# Ubuntu-ja translation of update-manager.
# Copyright (C) 2006 THE update-manager'S COPYRIGHT HOLDER
# This file is distributed under the same license as the update-manager package.
# Ikuya Awashiro <ikuya@fruitsbasket.info>, 2006.
# Hiroyuki Ikezoe <ikezoe@good-day.co.jp>, 2005
#
#
msgid ""
msgstr ""
"Project-Id-Version: update-manager 0.42.4\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2010-04-07 11:35+0200\n"
"PO-Revision-Date: 2010-03-24 14:21+0000\n"
"Last-Translator: Fumihito YOSHIDA <hito@kugutsu.org>\n"
"Language-Team: Ubuntu Japanese Team <ubuntu-ja-users@freeml.com>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Launchpad-Export-Date: 2010-04-07 08:08+0000\n"
"X-Generator: Launchpad (build Unknown)\n"

#. TRANSLATORS: download size is 0
#: ../DistUpgrade/utils.py:336 ../UpdateManager/Core/utils.py:336
msgid "0 KB"
msgstr "0 KB"

#. TRANSLATORS: download size of very small updates
#: ../DistUpgrade/utils.py:339 ../UpdateManager/Core/utils.py:339
msgid "1 KB"
msgstr "1 KB"

#. TRANSLATORS: download size of small updates, e.g. "250 KB"
#: ../DistUpgrade/utils.py:342 ../UpdateManager/Core/utils.py:342
#, python-format
msgid "%.0f KB"
msgstr "%.0f KB"

#. TRANSLATORS: download size of updates, e.g. "2.3 MB"
#: ../DistUpgrade/utils.py:345 ../UpdateManager/Core/utils.py:345
#, python-format
msgid "%.1f MB"
msgstr "%.1f MB"

#. TRANSLATORS: %s is a country
#: ../DistUpgrade/distro.py:208 ../DistUpgrade/distro.py:423
#, python-format
msgid "Server for %s"
msgstr "%s のサーバ"

#. More than one server is used. Since we don't handle this case
#. in the user interface we set "custom servers" to true and
#. append a list of all used servers
#: ../DistUpgrade/distro.py:226 ../DistUpgrade/distro.py:232
#: ../DistUpgrade/distro.py:248
msgid "Main server"
msgstr "メインサーバ"

#: ../DistUpgrade/distro.py:252
msgid "Custom servers"
msgstr "カスタムサーバ"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:131
msgid "Could not calculate sources.list entry"
msgstr "sources.listのエントリから作業内容を見積もれません"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:234
msgid ""
"Unable to locate any package files, perhaps this is not a Ubuntu Disc or the "
"wrong architecture?"
msgstr ""
"パッケージファイルが見つかりません。UbuntuのCDではないか、異なるアーキテク"
"チャ向けのCDかもしれません。"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:277
msgid "Failed to add the CD"
msgstr "CDの追加に失敗しました"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:278
#, python-format
msgid ""
"There was a error adding the CD, the upgrade will abort. Please report this "
"as a bug if this is a valid Ubuntu CD.\n"
"\n"
"The error message was:\n"
"'%s'"
msgstr ""
"CD をリソースとして追加できなかったため、アップグレードは終了されます。この "
"CD が正規の Ubuntu CD の場合は、このことをバグとして報告してください。\n"
"\n"
"エラーメッセージ：\n"
"'%s'"

#: ../DistUpgrade/DistUpgradeCache.py:130
msgid "Remove package in bad state"
msgid_plural "Remove packages in bad state"
msgstr[0] "壊れた状態のパッケージを削除する"

#: ../DistUpgrade/DistUpgradeCache.py:133
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Do you want to remove this package now "
"to continue?"
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archives can be found for them. Do you want to remove these packages "
"now to continue?"
msgstr[0] ""
"パッケージ '%s' は 矛盾した状態にあり再インストールが必要ですが、そのための"
"アーカイブを見つけることができません。 このパッケージを削除して先に進めます"
"か？"

#. FIXME: not ideal error message, but we just reuse a
#. existing one here to avoid a new string
#: ../DistUpgrade/DistUpgradeCache.py:231
msgid "The server may be overloaded"
msgstr "サーバーが過負荷状態にある可能性があります"

#: ../DistUpgrade/DistUpgradeCache.py:341
msgid "Broken packages"
msgstr "壊れたパッケージ"

#: ../DistUpgrade/DistUpgradeCache.py:342
msgid ""
"Your system contains broken packages that couldn't be fixed with this "
"software. Please fix them first using synaptic or apt-get before proceeding."
msgstr ""
"システムにはこのソフトウェアでは修復できない壊れたパッケージが含まれていま"
"す。 先に進む前に、\r\n"
"まず Synaptic や apt-get を使って問題を修正してください。"

#. FIXME: change the text to something more useful
#: ../DistUpgrade/DistUpgradeCache.py:621
#, python-format
msgid ""
"An unresolvable problem occurred while calculating the upgrade:\n"
"%s\n"
"\n"
" This can be caused by:\n"
" * Upgrading to a pre-release version of Ubuntu\n"
" * Running the current pre-release version of Ubuntu\n"
" * Unofficial software packages not provided by Ubuntu\n"
"\n"
msgstr ""
"アップグレードの見積もり中に解決できない問題が発生しました:\n"
"%s\n"
"\n"
" 以下の原因が考えられます:\n"
" * Ubuntu のリリース前バージョンへアップグレードしようとしている。\n"
" * Ubuntu のリリース前バージョンを使っている。\n"
" * Ubuntu が提供していない、非公式なパッケージを利用している。\n"
"\n"

#: ../DistUpgrade/DistUpgradeCache.py:631
msgid "This is most likely a transient problem, please try again later."
msgstr "これは一時的な問題のようです。後でもう一度試してください。"

#: ../DistUpgrade/DistUpgradeCache.py:634
msgid ""
"If none of this applies, then please report this bug against the 'update-"
"manager' package and include the files in /var/log/dist-upgrade/ in the bug "
"report."
msgstr ""
"これがどれも適用されないのであれば、'update-manager' パッケージに対するバグと"
"して、/var/log/dist-upgrade/ にあるファイルを含めて報告してください。"

#: ../DistUpgrade/DistUpgradeCache.py:640
#: ../UpdateManager/UpdateManager.py:766
msgid "Could not calculate the upgrade"
msgstr "アップグレードが算定できません"

#: ../DistUpgrade/DistUpgradeCache.py:690
msgid "Error authenticating some packages"
msgstr "いくつかのパッケージが認証されませんでした"

#: ../DistUpgrade/DistUpgradeCache.py:691
msgid ""
"It was not possible to authenticate some packages. This may be a transient "
"network problem. You may want to try again later. See below for a list of "
"unauthenticated packages."
msgstr ""
"いくつかのパッケージが認証できませんでした。これは一時的なネットワークの問題"
"かもしれません。あとで再び試してみてください。以下に認証できなかったパッケー"
"ジのリストが表示されます。"

#: ../DistUpgrade/DistUpgradeCache.py:711
#, python-format
msgid ""
"The package '%s' is marked for removal but it is in the removal blacklist."
msgstr ""
"パッケージ'%s'は「削除」と指定されていますが、削除ブラックリストに入っていま"
"す。"

#: ../DistUpgrade/DistUpgradeCache.py:715
#, python-format
msgid "The essential package '%s' is marked for removal."
msgstr "必須パッケージ'%s'に「削除」マークがついています。"

#: ../DistUpgrade/DistUpgradeCache.py:724
#, python-format
msgid "Trying to install blacklisted version '%s'"
msgstr ""
"ブラックリストに入っているバージョン '%s' をインストールしようとしています"

#: ../DistUpgrade/DistUpgradeCache.py:824
#, python-format
msgid "Can not mark '%s' for upgrade"
msgstr "'%s'を「アップグレード」指定できません。"

#: ../DistUpgrade/DistUpgradeCache.py:838
#, python-format
msgid "Can't install '%s'"
msgstr "'%s'をインストールすることができません。"

#: ../DistUpgrade/DistUpgradeCache.py:839
msgid ""
"It was impossible to install a required package. Please report this as a "
"bug. "
msgstr ""
"要求されたパッケージのインストールができません。バグとして報告してください。 "

#. FIXME: provide a list
#: ../DistUpgrade/DistUpgradeCache.py:848
msgid "Can't guess meta-package"
msgstr "メタパッケージを推測できません"

#: ../DistUpgrade/DistUpgradeCache.py:849
msgid ""
"Your system does not contain a ubuntu-desktop, kubuntu-desktop, xubuntu-"
"desktop or edubuntu-desktop package and it was not possible to detect which "
"version of Ubuntu you are running.\n"
" Please install one of the packages above first using synaptic or apt-get "
"before proceeding."
msgstr ""
"システムに ubuntu-desktop, kubuntu-desktop, xubuntu-desktop, もしくは"
"edubuntu-desktop パッケージが含まれていません。このため、実行している ubuntu "
"のバージョンが検出できません。 \n"
" 続ける前に、Synaptic や apt-get を使用して、まずは上記のパッケージのうちのい"
"ずれかをインストールしてください。"

#: ../DistUpgrade/DistUpgradeController.py:86
msgid "Reading cache"
msgstr "キャッシュを読み込み中です"

#: ../DistUpgrade/DistUpgradeController.py:189
msgid "Unable to get exclusive lock"
msgstr "排他的なロックができません"

#: ../DistUpgrade/DistUpgradeController.py:190
msgid ""
"This usually means that another package management application (like apt-get "
"or aptitude) already running. Please close that application first."
msgstr ""
"パッケージマネージャは一度にひとつしか起動できません。apt-getやaptitudeなどの"
"ような、他のパッケージマネージャを終了してください。"

#: ../DistUpgrade/DistUpgradeController.py:236
msgid "Upgrading over remote connection not supported"
msgstr "リモート接続越しでのアップグレードはサポートされていません"

#: ../DistUpgrade/DistUpgradeController.py:237
msgid ""
"You are running the upgrade over a remote ssh connection with a frontend "
"that does not support this. Please try a text mode upgrade with 'do-release-"
"upgrade'.\n"
"\n"
"The upgrade will abort now. Please try without ssh."
msgstr ""
"このアップグレード処理は、リモートSSH上で実行されたフロントエンドGUIから実行"
"されているようです。このツールはそうした処理をサポートしていません。\n"
"もしリモートからのアップグレードを望むなら、テキストモードによるアップグレー"
"ドを'do-release-upgrade' を用いて試してみてください。\n"
"\n"
"アップグレードは中断されます。SSHを経由しない起動方法で実行してください。"

#: ../DistUpgrade/DistUpgradeController.py:251
msgid "Continue running under SSH?"
msgstr "SSH越しに実行していますが、続けますか？"

#: ../DistUpgrade/DistUpgradeController.py:252
#, python-format
msgid ""
"This session appears to be running under ssh. It is not recommended to "
"perform a upgrade over ssh currently because in case of failure it is harder "
"to recover.\n"
"\n"
"If you continue, an additional ssh daemon will be started at port '%s'.\n"
"Do you want to continue?"
msgstr ""
"このセッションはSSH上で実行されているようです。アップグレードをSSH越しに行う"
"ことは推奨されません。アップグレードに失敗した時の復元が困難になるからで"
"す。\n"
"\n"
"続行する場合、追加のSSHデーモンをポート '%s' で起動します。\n"
"本当に作業を進めてよろしいですか？"

#: ../DistUpgrade/DistUpgradeController.py:267
msgid "Starting additional sshd"
msgstr "予備のsshdを開始します"

#: ../DistUpgrade/DistUpgradeController.py:268
#, python-format
msgid ""
"To make recovery in case of failure easier, an additional sshd will be "
"started on port '%s'. If anything goes wrong with the running ssh you can "
"still connect to the additional one.\n"
msgstr ""
"障害が起こったときに復旧しやすくするため、ポート '%s' でもう一つの sshd を開"
"始します。現在実行中のsshにおかしなことが起きても、もう一方のポートに接続する"
"ことができます。\n"

#: ../DistUpgrade/DistUpgradeController.py:339
#: ../DistUpgrade/DistUpgradeController.py:384
msgid "Can not upgrade"
msgstr "アップグレードできません"

#: ../DistUpgrade/DistUpgradeController.py:340
#, python-format
msgid "An upgrade from '%s' to '%s' is not supported with this tool."
msgstr ""
"'%s' から '%s' へのアップグレードは、このツールではサポートされていません。"

#: ../DistUpgrade/DistUpgradeController.py:349
msgid "Sandbox setup failed"
msgstr "サンドボックス環境のセットアップに失敗しました"

#: ../DistUpgrade/DistUpgradeController.py:350
msgid "It was not possible to create the sandbox environment."
msgstr "サンドボックス環境を構築することができませんでした。"

#: ../DistUpgrade/DistUpgradeController.py:356
msgid "Sandbox mode"
msgstr "サンドボックスモード"

#: ../DistUpgrade/DistUpgradeController.py:357
#, python-format
msgid ""
"This upgrade is running in sandbox (test) mode. All changes are written to '%"
"s' and will be lost on the next reboot.\n"
"\n"
"*No* changes written to a systemdir from now until the next reboot are "
"permanent."
msgstr ""
"このアップグレードはサンドボックス(テスト)モードで実行されています。あらゆる"
"変更は '%s' に書き込まれ、次の再起動時に消されます。\n"
"\n"
"現在から次の再起動までにシステムディレクトリに書き込まれる変更は、あくまで一"
"時的なものです。"

#: ../DistUpgrade/DistUpgradeController.py:385
msgid ""
"Your python install is corrupted. Please fix the '/usr/bin/python' symlink."
msgstr ""
"インストールされたPythonが破損しています。シンボリックリンク'/usr/bin/"
"python'を修正してください。"

#: ../DistUpgrade/DistUpgradeController.py:411
msgid "Package 'debsig-verify' is installed"
msgstr "'debsig-verify'パッケージがインストールされています"

#: ../DistUpgrade/DistUpgradeController.py:412
msgid ""
"The upgrade can not continue with that package installed.\n"
"Please remove it with synaptic or 'apt-get remove debsig-verify' first and "
"run the upgrade again."
msgstr ""
"'debsig-verify'パッケージがインストールされていると、アップグレードを継続する"
"ことができません。\n"
"Synapticパッケージ・マネージャか 'apt-get remove debsig-verify' で削除した後"
"で、再度アップグレードを実行してください。"

#: ../DistUpgrade/DistUpgradeController.py:422
msgid "Include latest updates from the Internet?"
msgstr "インターネットからの最新のアップデート情報を取得しますか？"

#: ../DistUpgrade/DistUpgradeController.py:423
msgid ""
"The upgrade system can use the internet to automatically download the latest "
"updates and install them during the upgrade.  If you have a network "
"connection this is highly recommended.\n"
"\n"
"The upgrade will take longer, but when it is complete, your system will be "
"fully up to date.  You can choose not to do this, but you should install the "
"latest updates soon after upgrading.\n"
"If you answer 'no' here, the network is not used at all."
msgstr ""
"アップグレードシステムは、ネットワークを利用したシステムのアップグレードに対"
"応しています。最新のパッケージを自動的にダウンロードし、アップグレード時に併"
"せてインストールできるため、ネットワークへの接続が可能なら、この方法を使うこ"
"とを強く推奨します。\n"
"\n"
"アップグレードには時間がかかりますが、ネットワークを利用すれば、完了時に最新"
"のアップデータが導入された状態になります。ネットワークを利用しないアップグ"
"レードも可能ですが、この場合はアップグレードが完了した後で、さらにアップデー"
"タをインストールする必要があります。\n"
"ここで「いいえ」を選択すると、アップグレードにネットワークを利用しません。"

#: ../DistUpgrade/DistUpgradeController.py:647
#, python-format
msgid "disabled on upgrade to %s"
msgstr "%sへのアップグレード時に無効化されました"

#: ../DistUpgrade/DistUpgradeController.py:674
msgid "No valid mirror found"
msgstr "利用可能なミラーが見つかりません"

#: ../DistUpgrade/DistUpgradeController.py:675
#, python-format
msgid ""
"While scanning your repository information no mirror entry for the upgrade "
"was found. This can happen if you run a internal mirror or if the mirror "
"information is out of date.\n"
"\n"
"Do you want to rewrite your 'sources.list' file anyway? If you choose 'Yes' "
"here it will update all '%s' to '%s' entries.\n"
"If you select 'No' the upgrade will cancel."
msgstr ""
"システムに設定されたリポジトリ情報を確認しましたが、アップグレードに利用可能"
"なミラーサーバーのエントリが見つかりませんでした。プライベートなミラーサー"
"バーを利用していたり、ミラー情報が古い可能性があります。\n"
"\n"
"ミラーサーバーの設定ファイル 'souces.list' をとにかく編集しますか？　「はい」"
"を選択すると、'%s' エントリは '%s' に置き換わります。\n"
"「いいえ」を選択すると、アップグレードをキャンセルします。"

#. hm, still nothing useful ...
#: ../DistUpgrade/DistUpgradeController.py:695
msgid "Generate default sources?"
msgstr "標準のリポジトリ設定ファイルを生成しますか？"

#: ../DistUpgrade/DistUpgradeController.py:696
#, python-format
msgid ""
"After scanning your 'sources.list' no valid entry for '%s' was found.\n"
"\n"
"Should default entries for '%s' be added? If you select 'No', the upgrade "
"will cancel."
msgstr ""
"システムの 'sources.list' を確認しましたが、有効な '%s' のためのエントリが見"
"つかりません。\n"
"\n"
"'%s' のためのデフォルト設定エントリを追加しますか？　「いいえ」を選択すると、"
"アップグレードはキャンセルされます。"

#: ../DistUpgrade/DistUpgradeController.py:731
msgid "Repository information invalid"
msgstr "リポジトリ情報が無効です"

#: ../DistUpgrade/DistUpgradeController.py:732
msgid ""
"Upgrading the repository information resulted in a invalid file. Please "
"report this as a bug."
msgstr ""
"リポジトリ情報のアップグレード時に、利用不能なファイルが生成されました。バグ"
"として報告してください。"

#: ../DistUpgrade/DistUpgradeController.py:738
msgid "Third party sources disabled"
msgstr "サードパーティが提供するリポジトリを使わない設定にしました"

#: ../DistUpgrade/DistUpgradeController.py:739
msgid ""
"Some third party entries in your sources.list were disabled. You can re-"
"enable them after the upgrade with the 'software-properties' tool or your "
"package manager."
msgstr ""
"sources.list にあるサードパーティが提供するリポジトリを使わない設定にしまし"
"た。アップグレード完了後、'ソフトウェア・ソース' ツールもしくはパッケージ・マ"
"ネージャを使って再び利用可能な設定にすることができます。"

#: ../DistUpgrade/DistUpgradeController.py:779
msgid "Package in inconsistent state"
msgid_plural "Packages in inconsistent state"
msgstr[0] "矛盾した状態のパッケージ"

#: ../DistUpgrade/DistUpgradeController.py:782
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Please reinstall the package manually or "
"remove it from the system."
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archive can be found for them. Please reinstall the packages manually "
"or remove them from the system."
msgstr[0] ""
"パッケージ '%s' は 矛盾した状態にあり再インストールが必要ですが、そのための"
"アーカイブを見つけることができません。パッケージを手動で再インストールする"
"か、システムからパッケージを削除してください。"

#: ../DistUpgrade/DistUpgradeController.py:830
msgid "Error during update"
msgstr "アップデート中にエラーが発生しました"

#: ../DistUpgrade/DistUpgradeController.py:831
msgid ""
"A problem occurred during the update. This is usually some sort of network "
"problem, please check your network connection and retry."
msgstr ""
"アップデート中に問題が発生しました。通常、これはネットワークにおける何らかの"
"問題です。ネットワーク接続が可能であることをチェックし、あらためて試してくだ"
"さい。"

#. print "on_button_install_clicked"
#: ../DistUpgrade/DistUpgradeController.py:840
#: ../UpdateManager/UpdateManager.py:573
msgid "Not enough free disk space"
msgstr "ディスクの空き領域が足りません"

#: ../DistUpgrade/DistUpgradeController.py:841
#, python-format
msgid ""
"The upgrade is now aborted. The upgrade needs a total of %s free space on "
"disk '%s'. Please free at least an additional %s of disk space on '%s'. "
"Empty your trash and remove temporary packages of former installations using "
"'sudo apt-get clean'."
msgstr ""
"アップグレードを中止しました。アップグレードには%sの空き容量がディスク'%s'に"
"必要です。あと%sの空き容量を'%s'に確保してください。ゴミ箱を空にした"
"り、'sudo apt-get clean'を使って、以前にインストールした一時的なパッケージを"
"削除したりしてください。"

#. calc the dist-upgrade and see if the removals are ok/expected
#. do the dist-upgrade
#: ../DistUpgrade/DistUpgradeController.py:869
#: ../DistUpgrade/DistUpgradeController.py:1607
msgid "Calculating the changes"
msgstr "変更点を取得中"

#: ../DistUpgrade/DistUpgradeController.py:885
msgid ""
"Canonical Ltd. no longer provides support for the following software "
"packages. You can still get support from the community."
msgstr ""
"今後は Canonical Ltd. は以下のソフトウェアパッケージのサポートを行ないませ"
"ん。引き続きコミュニティからサポートされます。"

#: ../DistUpgrade/DistUpgradeController.py:892
msgid ""
"Canonical Ltd. no longer provides support for the following software "
"packages. You can still get support from the community.\n"
"\n"
"These packages will be suggested for removal at the end of the upgrade "
"because you have not enabled the community maintained software channel "
"(universe)."
msgstr ""
"今後は Canonical Ltd. は以下のソフトウェアパッケージのサポートを行ないませ"
"ん。引き続きコミュニティからサポートされます。"

#: ../DistUpgrade/DistUpgradeController.py:900
msgid "Support for some applications ended"
msgstr "いくつかのアプリケーションのサポートは終了しました"

#. ask the user if he wants to do the changes
#: ../DistUpgrade/DistUpgradeController.py:920
msgid "Do you want to start the upgrade?"
msgstr "アップグレードを開始しますか？"

#: ../DistUpgrade/DistUpgradeController.py:985
msgid "Upgrade canceled"
msgstr "アップグレードをキャンセルしました"

#: ../DistUpgrade/DistUpgradeController.py:986
msgid ""
"The upgrade cancels now and the original system state is restored. You can "
"resume the upgrade at a later time."
msgstr ""
"アップグレードをキャンセルし、システムを元の状態に復元しました。アップグレー"
"ドは後で再開できます。"

#: ../DistUpgrade/DistUpgradeController.py:991
#: ../DistUpgrade/DistUpgradeController.py:1094
msgid "Could not download the upgrades"
msgstr "アップグレードに必要なデータをダウンロードできません"

#: ../DistUpgrade/DistUpgradeController.py:992
msgid ""
"The upgrade is now aborted. Please check your Internet connection or "
"installation media and try again. All files downloaded so far are kept."
msgstr ""
"現在アップグレードは中断されています。インターネット接続やインストールメディ"
"アを確認してもう一度試してください。これまでにダウンロードしたファイルはすべ"
"て保存されています。"

#. FIXME: strings are not good, but we are in string freeze
#. currently
#: ../DistUpgrade/DistUpgradeController.py:1049
#: ../DistUpgrade/DistUpgradeController.py:1082
#: ../DistUpgrade/DistUpgradeController.py:1187
msgid "Error during commit"
msgstr "反映中にエラーが発生しました"

#. generate a new cache
#: ../DistUpgrade/DistUpgradeController.py:1051
#: ../DistUpgrade/DistUpgradeController.py:1084
#: ../DistUpgrade/DistUpgradeController.py:1226
msgid "Restoring original system state"
msgstr "システムを元に戻しています"

#: ../DistUpgrade/DistUpgradeController.py:1052
#: ../DistUpgrade/DistUpgradeController.py:1066
#: ../DistUpgrade/DistUpgradeController.py:1085
msgid "Could not install the upgrades"
msgstr "アップグレードをインストールできません"

#. invoke the frontend now and show a error message
#: ../DistUpgrade/DistUpgradeController.py:1057
msgid ""
"The upgrade is now aborted. Your system could be in an unusable state. A "
"recovery will run now (dpkg --configure -a)."
msgstr ""
"現在アップグレードは中断されています。システムが使用できない状態である可能性"
"があります。今から回復を実行します。 (dpkg --configure -a)"

#: ../DistUpgrade/DistUpgradeController.py:1062
#, python-format
msgid ""
"\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"files in /var/log/dist-upgrade/ in the bug report.\n"
"%s"
msgstr ""
"\n"
"\n"
"このバグを 'update-manager' パッケージに対するバグとして、/var/log/dist-"
"upgrade/ にあるファイルをバグレポートに含めて報告してください。\n"
"%s"

#: ../DistUpgrade/DistUpgradeController.py:1095
msgid ""
"The upgrade is now aborted. Please check your Internet connection or "
"installation media and try again. "
msgstr ""
"現在アップグレードは中断されています。インターネット接続やインストールメディ"
"アを確認してもう一度試してください。 "

#: ../DistUpgrade/DistUpgradeController.py:1175
msgid "Remove obsolete packages?"
msgstr ""
"サポートが中止された（あるいはリポジトリに存在しない）パッケージを削除します"
"か？"

#: ../DistUpgrade/DistUpgradeController.py:1176
#: ../DistUpgrade/DistUpgrade.ui.h:22
msgid "_Keep"
msgstr "そのまま(_K)"

#: ../DistUpgrade/DistUpgradeController.py:1176
msgid "_Remove"
msgstr "削除(_R)"

#: ../DistUpgrade/DistUpgradeController.py:1188
msgid ""
"A problem occurred during the clean-up. Please see the below message for "
"more information. "
msgstr ""
"クリーンアップ中に問題が発生しました。詳細情報は下記のメッセージを参照してく"
"ださい。 "

#. FIXME: instead of error out, fetch and install it
#. here
#: ../DistUpgrade/DistUpgradeController.py:1264
msgid "Required depends is not installed"
msgstr "依存するパッケージがインストールされていません"

#: ../DistUpgrade/DistUpgradeController.py:1265
#, python-format
msgid "The required dependency '%s' is not installed. "
msgstr "依存するパッケージ '%s' がインストールされていません。 "

#. sanity check (check for ubuntu-desktop, brokenCache etc)
#. then open the cache (again)
#: ../DistUpgrade/DistUpgradeController.py:1510
#: ../DistUpgrade/DistUpgradeController.py:1577
msgid "Checking package manager"
msgstr "パッケージ・マネージャをチェック中です"

#: ../DistUpgrade/DistUpgradeController.py:1515
msgid "Preparing the upgrade failed"
msgstr "アップグレードの準備に失敗しました"

#: ../DistUpgrade/DistUpgradeController.py:1516
msgid ""
"Preparing the system for the upgrade failed. Please report this as a bug "
"against the 'update-manager' package and include the files in /var/log/dist-"
"upgrade/ in the bug report."
msgstr ""
"アップグレードのための準備に失敗しました。このことを 'update-manager' パッ"
"ケージに対するバグとして、/var/log/dist-upgrade/ にあるファイル群をバグレポー"
"トに含めて報告してください。"

#: ../DistUpgrade/DistUpgradeController.py:1532
msgid "Getting upgrade prerequisites failed"
msgstr "アップグレードの事前作業に失敗しました"

#: ../DistUpgrade/DistUpgradeController.py:1533
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"Please report this as a bug against the 'update-manager' package and include "
"the files in /var/log/dist-upgrade/ in the bug report."
msgstr ""
"システムはアップグレードの事前作業に失敗しました。アップグレードを中断して、"
"システムを元の状態に戻しました。\n"
"\n"
"このことを 'update-manager' パッケージに対するバグとして、/var/log/dist-"
"upgrade/ にあるファイルをバグレポートに含めて報告してください。"

#: ../DistUpgrade/DistUpgradeController.py:1563
msgid "Updating repository information"
msgstr "リポジトリ情報のアップデート"

#: ../DistUpgrade/DistUpgradeController.py:1595
msgid "Invalid package information"
msgstr "利用できないパッケージ情報です"

#: ../DistUpgrade/DistUpgradeController.py:1596
#, python-format
msgid ""
"After your package information was updated the essential package '%s' can "
"not be found anymore.\n"
"This indicates a serious error, please report this bug against the 'update-"
"manager' package and include the files in /var/log/dist-upgrade/ in the bug "
"report."
msgstr ""
"パッケージ情報が更新されましたが、「essential」（必須）に属するパッケージ '%"
"s' がどこにも見つかりません。\n"
"これは深刻なエラーを意味しますので、'update-manager' パッケージに対するバグと"
"して、/var/log/dist-upgrade/ にあるファイルの内容をバグレポートに含めて報告し"
"てください。"

#: ../DistUpgrade/DistUpgradeController.py:1613
#: ../DistUpgrade/DistUpgradeController.py:1661
msgid "Fetching"
msgstr "取得中"

#: ../DistUpgrade/DistUpgradeController.py:1619
#: ../DistUpgrade/DistUpgradeController.py:1665
msgid "Upgrading"
msgstr "アップグレード中です"

#. don't abort here, because it would restore the sources.list
#: ../DistUpgrade/DistUpgradeController.py:1624
#: ../DistUpgrade/DistUpgradeController.py:1667
#: ../DistUpgrade/DistUpgradeController.py:1674
#: ../DistUpgrade/DistUpgradeController.py:1685
msgid "Upgrade complete"
msgstr "アップグレードが完了しました"

#: ../DistUpgrade/DistUpgradeController.py:1625
#: ../DistUpgrade/DistUpgradeController.py:1668
#: ../DistUpgrade/DistUpgradeController.py:1675
msgid ""
"The upgrade is completed but there were errors during the upgrade process."
msgstr ""
"アップグレードは完了しましたが、アップグレード処理中にエラーが確認されまし"
"た。"

#: ../DistUpgrade/DistUpgradeController.py:1632
msgid "Searching for obsolete software"
msgstr "古いソフトウェアを検索しています"

#: ../DistUpgrade/DistUpgradeController.py:1637
msgid "System upgrade is complete."
msgstr "システムのアップグレードが完了しました。"

#: ../DistUpgrade/DistUpgradeController.py:1686
msgid "The partial upgrade was completed."
msgstr "部分的なアップグレードが完了しました。"

#: ../DistUpgrade/DistUpgradeQuirks.py:168
msgid "evms in use"
msgstr "evms は使用中です"

#: ../DistUpgrade/DistUpgradeQuirks.py:169
msgid ""
"Your system uses the 'evms' volume manager in /proc/mounts. The 'evms' "
"software is no longer supported, please switch it off and run the upgrade "
"again when this is done."
msgstr ""
"システムは/proc/mountsでボリュームマネジャとして 'evms' を使っていま"
"す。'evms' ソフトウェアはもうサポートされていません。オフにしてからアップグ"
"レードしてください。"

#: ../DistUpgrade/DistUpgradeQuirks.py:423
#: ../DistUpgrade/DistUpgradeQuirks.py:451
#: ../DistUpgrade/DistUpgradeQuirks.py:478
msgid ""
"Upgrading may reduce desktop effects, and performance in games and other "
"graphically intensive programs."
msgstr ""
"アップグレードによって、デスクトップ効果（3Dデスクトップ）やゲーム、グラ"
"フィックに強く依存するその他のプログラムなどのパフォーマンスが低下するかもし"
"れません。"

#: ../DistUpgrade/DistUpgradeQuirks.py:427
#: ../DistUpgrade/DistUpgradeQuirks.py:455
msgid ""
"This computer is currently using the NVIDIA 'nvidia' graphics driver. No "
"version of this driver is available that works with your video card in "
"Ubuntu 10.04 LTS.\n"
"\n"
"Do you want to continue?"
msgstr ""
"現在、このコンピュータはNVIDIA 'nvidia' グラフィックドライバを利用していま"
"す。Ubuntu 10.04 LTS では、このハードウェアで動作可能なドライバのバージョンはあり"
"ません。\n"
"\n"
"作業を続けますか？"

#: ../DistUpgrade/DistUpgradeQuirks.py:482
msgid ""
"This computer is currently using the AMD 'fglrx' graphics driver. No version "
"of this driver is available that works with your hardware in Ubuntu 10.04 "
"LTS.\n"
"\n"
"Do you want to continue?"
msgstr ""
"現在、このコンピュータはAMD 'fglrx' グラフィックドライバを利用しています。"
"Ubuntu 10.04 LTS では、このハードウェアで動作可能なドライバのバージョンはありませ"
"ん。\n"
"\n"
"作業を続けますか？"

#: ../DistUpgrade/DistUpgradeQuirks.py:509
msgid "No ARMv6 CPU"
msgstr "ARMv6 準拠ではない CPU です"

#: ../DistUpgrade/DistUpgradeQuirks.py:510
msgid ""
"Your system uses an ARM CPU that is older than the ARMv6 architecture. All "
"packages in karmic were built with optimizations requiring ARMv6 as the "
"minimal architecture. It is not possible to upgrade your system to a new "
"Ubuntu release with this hardware."
msgstr ""
"このシステムでは ARM CPU が使われていますが、ARMv6 アーキテクチャより古いもの"
"のようです。karmic の全てのパッケージは、ARMv6 アーキテクチャへの対応が必須な"
"最適化オプションを利用してビルドされています。このハードウェアでは新しい "
"Ubuntu のリリースにアップグレードできません。"

#: ../DistUpgrade/DistUpgradeQuirks.py:530
msgid "No init available"
msgstr "initデーモンが見つかりません"

#: ../DistUpgrade/DistUpgradeQuirks.py:531
msgid ""
"Your system appears to be a virtualised environment without an init daemon, "
"e.g. Linux-VServer. Ubuntu 10.04 LTS cannot function within this type of "
"environment, requiring an update to your virtual machine configuration "
"first.\n"
"\n"
"Are you sure you want to continue?"
msgstr ""
"このシステムは、initデーモンの関与なしで稼働している仮想環境のようです（例："
"Linux-VServer）。 Ubuntu 10.04 LTS ではこのタイプの環境を稼働させることができませ"
"ん。アップグレードの前に、仮想マシン設定を設定しなおす必要があります。\n"
"\n"
"本当に作業を進めてよろしいですか？"

#: ../DistUpgrade/DistUpgradeMain.py:43
msgid "Sandbox upgrade using aufs"
msgstr "aufsを使用したサンドボックスアップグレード"

#: ../DistUpgrade/DistUpgradeMain.py:45
msgid "Use the given path to search for a cdrom with upgradable packages"
msgstr "アップグレードパッケージが含まれたCD-ROMへのパスを指定してください"

#: ../DistUpgrade/DistUpgradeMain.py:51
msgid ""
"Use frontend. Currently available: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"
msgstr ""
"フロントエンドを使用してください。現在利用可能なもの: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"

#: ../DistUpgrade/DistUpgradeMain.py:54
msgid "*DEPRECATED* this option will be ignore"
msgstr "*非推奨* このオプションは無視されます"

#: ../DistUpgrade/DistUpgradeMain.py:57
msgid "Perform a partial upgrade only (no sources.list rewriting)"
msgstr "部分アップグレードだけを実行します（sources.listを書き換えません）"

#: ../DistUpgrade/DistUpgradeMain.py:59
msgid "Set datadir"
msgstr "datadirを設定"

#. print "mediaChange %s %s" % (medium, drive)
#: ../DistUpgrade/DistUpgradeViewGtk.py:109
#: ../DistUpgrade/DistUpgradeViewKDE.py:190
#: ../UpdateManager/DistUpgradeFetcherKDE.py:148
#, python-format
msgid "Please insert '%s' into the drive '%s'"
msgstr "メディア '%s' をドライブ '%s' に挿入してください"

#: ../DistUpgrade/DistUpgradeViewGtk.py:129
#: ../DistUpgrade/DistUpgradeViewKDE.py:204
msgid "Fetching is complete"
msgstr "取得が完了しました"

#: ../DistUpgrade/DistUpgradeViewGtk.py:141
#: ../DistUpgrade/DistUpgradeViewKDE.py:217
#, python-format
msgid "Fetching file %li of %li at %sB/s"
msgstr "%li / %li を取得中（%s B/s）"

#: ../DistUpgrade/DistUpgradeViewGtk.py:142
#: ../DistUpgrade/DistUpgradeViewGtk.py:277
#: ../DistUpgrade/DistUpgradeViewKDE.py:218
#: ../DistUpgrade/DistUpgradeViewKDE.py:358
#, python-format
msgid "About %s remaining"
msgstr "残り時間 約%s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:144
#: ../DistUpgrade/DistUpgradeViewKDE.py:220
#, python-format
msgid "Fetching file %li of %li"
msgstr "%li / %li を取得中です"

#. FIXME: add support for the timeout
#. of the terminal (to display something useful then)
#. -> longer term, move this code into python-apt
#: ../DistUpgrade/DistUpgradeViewGtk.py:176
#: ../DistUpgrade/DistUpgradeViewKDE.py:254
msgid "Applying changes"
msgstr "変更を適用しています"

#. we do not report followup errors from earlier failures
#: ../DistUpgrade/DistUpgradeViewGtk.py:201
#: ../DistUpgrade/DistUpgradeViewKDE.py:267
msgid "dependency problems - leaving unconfigured"
msgstr "依存関係の問題 - 設定を見送ります"

#: ../DistUpgrade/DistUpgradeViewGtk.py:206
#: ../DistUpgrade/DistUpgradeViewKDE.py:269
#, python-format
msgid "Could not install '%s'"
msgstr "'%s' がインストールできません"

#: ../DistUpgrade/DistUpgradeViewGtk.py:207
#: ../DistUpgrade/DistUpgradeViewKDE.py:270
#, python-format
msgid ""
"The upgrade will continue but the '%s' package may not be in a working "
"state. Please consider submitting a bug report about it."
msgstr ""
"アップグレードを続けますが、'%s' パッケージが動かない状態にある可能性がありま"
"す。この件に関してバグレポートを送信することを検討してください。"

#. self.expander.set_expanded(True)
#: ../DistUpgrade/DistUpgradeViewGtk.py:223
#: ../DistUpgrade/DistUpgradeViewKDE.py:291
#, python-format
msgid ""
"Replace the customized configuration file\n"
"'%s'?"
msgstr ""
"以下のカスタマイズ済みの設定ファイルを置き換えますか？\n"
"'%s'"

#: ../DistUpgrade/DistUpgradeViewGtk.py:224
#: ../DistUpgrade/DistUpgradeViewKDE.py:292
msgid ""
"You will lose any changes you have made to this configuration file if you "
"choose to replace it with a newer version."
msgstr ""
"より新しいバージョンと入れ換えた場合、この構成ファイルへの変更内容は失われま"
"す。"

#: ../DistUpgrade/DistUpgradeViewGtk.py:237
#: ../DistUpgrade/DistUpgradeViewKDE.py:310
msgid "The 'diff' command was not found"
msgstr "'diff' コマンドが見つかりません"

#: ../DistUpgrade/DistUpgradeViewGtk.py:442
#: ../DistUpgrade/DistUpgradeViewText.py:88
msgid "A fatal error occurred"
msgstr "致命的なエラーが起こりました"

#: ../DistUpgrade/DistUpgradeViewGtk.py:443
msgid ""
"Please report this as a bug (if you haven't already) and include the files /"
"var/log/dist-upgrade/main.log and /var/log/dist-upgrade/apt.log in your "
"report. The upgrade is now aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"(既に報告済でなければ)/var/log/dist-upgrade/main.log と /var/log/dist-"
"upgrade/apt.log も含めて、バグとして報告してください。アップグレードを中断し"
"ます。\n"
"元のソースリストは/etc/apt/sources.list.distUpgrade に保存されました。"

#: ../DistUpgrade/DistUpgradeViewGtk.py:460
msgid "Ctrl-c pressed"
msgstr "Ctrl-c が入力されました"

#: ../DistUpgrade/DistUpgradeViewGtk.py:461
msgid ""
"This will abort the operation and may leave the system in a broken state. "
"Are you sure you want to do that?"
msgstr ""
"これは操作を中断することになり、システムを壊れた状態にしてしまうかもしれませ"
"ん。本当に実行しますか？"

#. append warning
#: ../DistUpgrade/DistUpgradeViewGtk.py:606
msgid "To prevent data loss close all open applications and documents."
msgstr ""
"データが失われることを避けるため、利用中のアプリケーションとドキュメントを閉"
"じてください。"

#: ../DistUpgrade/DistUpgradeViewGtk.py:620
#, python-format
msgid "<b>Downgrade %s</b>"
msgstr "<b>ダウングレードされるパッケージ： %s</b>"

#: ../DistUpgrade/DistUpgradeViewGtk.py:622
#: ../DistUpgrade/DistUpgradeViewKDE.py:758
#, python-format
msgid "Remove %s"
msgstr "%s を削除"

#: ../DistUpgrade/DistUpgradeViewGtk.py:627
#: ../DistUpgrade/DistUpgradeViewKDE.py:760
#, python-format
msgid "Remove (was auto installed) %s"
msgstr "(自動インストールされた) %s を削除"

#: ../DistUpgrade/DistUpgradeViewGtk.py:630
#: ../DistUpgrade/DistUpgradeViewKDE.py:762
#, python-format
msgid "Install %s"
msgstr "インストール %s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:632
#: ../DistUpgrade/DistUpgradeViewKDE.py:764
#, python-format
msgid "Upgrade %s"
msgstr "アップグレード %s"

#. change = QMessageBox.question(None, _("Media Change"), msg, QMessageBox.Ok, QMessageBox.Cancel)
#: ../DistUpgrade/DistUpgradeViewKDE.py:191
#: ../UpdateManager/DistUpgradeFetcherKDE.py:150
msgid "Media Change"
msgstr "メディアの交換"

#: ../DistUpgrade/DistUpgradeViewKDE.py:322
msgid "Show Difference >>>"
msgstr "差分を表示 >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:325
msgid "<<< Hide Difference"
msgstr "<<< 差分を隠す"

#: ../DistUpgrade/DistUpgradeViewKDE.py:539
msgid "Error"
msgstr "エラー"

#: ../DistUpgrade/DistUpgradeViewKDE.py:551
msgid "&Cancel"
msgstr "キャンセル(&C)"

#: ../DistUpgrade/DistUpgradeViewKDE.py:553
#: ../DistUpgrade/DistUpgradeViewKDE.py:792
msgid "&Close"
msgstr "閉じる(&C)"

#: ../DistUpgrade/DistUpgradeViewKDE.py:599
msgid "Show Terminal >>>"
msgstr "端末を表示 >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:602
msgid "<<< Hide Terminal"
msgstr "<<< 端末を隠す"

#: ../DistUpgrade/DistUpgradeViewKDE.py:682
msgid "Information"
msgstr "情報"

#: ../DistUpgrade/DistUpgradeViewKDE.py:732
#: ../DistUpgrade/DistUpgradeViewKDE.py:775
#: ../DistUpgrade/DistUpgradeViewKDE.py:778 ../DistUpgrade/DistUpgrade.ui.h:11
msgid "Details"
msgstr "詳細"

#: ../DistUpgrade/DistUpgradeViewKDE.py:788
#: ../DistUpgrade/DistUpgradeViewText.py:206
msgid "Restart required"
msgstr "再起動が必要です"

#: ../DistUpgrade/DistUpgradeViewKDE.py:788
msgid "<b><big>Restart the system to complete the upgrade</big></b>"
msgstr ""
"<b><big>アップグレードを完了するためには、システムの再起動が必要です</big></"
"b>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:791 ../DistUpgrade/DistUpgrade.ui.h:25
#: ../data/glade/UpdateManager.ui.h:31
msgid "_Restart Now"
msgstr "すぐに再起動(_R)"

#. FIXME make this user friendly
#: ../DistUpgrade/DistUpgradeViewKDE.py:803
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly advised to resume the upgrade."
msgstr ""
"<b><big>実行中のアップグレードをキャンセルしますか？</big></b>\n"
"\n"
"アップグレードをキャンセルしてしまうと、システムが不安定な状態になる恐れがあ"
"ります。アップグレードを再開することを強くお勧めします。"

#: ../DistUpgrade/DistUpgradeViewKDE.py:807
msgid "Cancel Upgrade?"
msgstr "アップグレードをキャンセルしますか?"

#: ../DistUpgrade/DistUpgradeView.py:60
#, python-format
msgid "%li day"
msgid_plural "%li days"
msgstr[0] "%li 日"

#: ../DistUpgrade/DistUpgradeView.py:62
#, python-format
msgid "%li hour"
msgid_plural "%li hours"
msgstr[0] "%li 時間"

#: ../DistUpgrade/DistUpgradeView.py:64
#, python-format
msgid "%li minute"
msgid_plural "%li minutes"
msgstr[0] "%li 分"

#: ../DistUpgrade/DistUpgradeView.py:65
#, python-format
msgid "%li second"
msgid_plural "%li seconds"
msgstr[0] "%li 秒"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_days)s %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#.
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#.
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:78
#, python-format
msgid "%(str_days)s %(str_hours)s"
msgstr "%(str_days)s %(str_hours)s"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#.
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#.
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:93
#, python-format
msgid "%(str_hours)s %(str_minutes)s"
msgstr "%(str_hours)s %(str_minutes)s"

#. 56 kbit
#. 1Mbit = 1024 kbit
#: ../DistUpgrade/DistUpgradeView.py:128
#, python-format
msgid ""
"This download will take about %s with a 1Mbit DSL connection and about %s "
"with a 56k modem."
msgstr ""
"このダウンロードは 1Mbit DSL 接続で約 %s 、56k モデムで約 %s かかります。"

#. if we have a estimated speed, use it
#: ../DistUpgrade/DistUpgradeView.py:132
#, python-format
msgid "This download will take about %s with your connection. "
msgstr "このダウンロードは約 %s かかります。 "

#: ../DistUpgrade/DistUpgradeView.py:234 ../DistUpgrade/DistUpgrade.ui.h:16
msgid "Preparing to upgrade"
msgstr "アップグレードの準備"

#: ../DistUpgrade/DistUpgradeView.py:235
msgid "Getting new software channels"
msgstr "新しいソフトウェア・チャンネルの取得"

#: ../DistUpgrade/DistUpgradeView.py:236 ../DistUpgrade/DistUpgrade.ui.h:14
msgid "Getting new packages"
msgstr "新しいパッケージの取得"

#: ../DistUpgrade/DistUpgradeView.py:237 ../DistUpgrade/DistUpgrade.ui.h:15
msgid "Installing the upgrades"
msgstr "アップグレードのインストール"

#: ../DistUpgrade/DistUpgradeView.py:238 ../DistUpgrade/DistUpgrade.ui.h:10
msgid "Cleaning up"
msgstr "クリーンアップ"

#. FIXME: make those two separate lines to make it clear
#. that the "%" applies to the result of ngettext
#: ../DistUpgrade/DistUpgradeView.py:322
#, python-format
msgid "%d package is going to be removed."
msgid_plural "%d packages are going to be removed."
msgstr[0] "%d 個のパッケージが削除されます。"

#: ../DistUpgrade/DistUpgradeView.py:327
#, python-format
msgid "%d new package is going to be installed."
msgid_plural "%d new packages are going to be installed."
msgstr[0] "%d 個の新規パッケージがインストールされます。"

#: ../DistUpgrade/DistUpgradeView.py:333
#, python-format
msgid "%d package is going to be upgraded."
msgid_plural "%d packages are going to be upgraded."
msgstr[0] "%d 個のパッケージがアップグレードされます。"

#: ../DistUpgrade/DistUpgradeView.py:338
#, python-format
msgid ""
"\n"
"\n"
"You have to download a total of %s. "
msgstr ""
"\n"
"\n"
"合計 %s をダウンロードする必要があります。 "

#: ../DistUpgrade/DistUpgradeView.py:342
msgid ""
"Fetching and installing the upgrade can take several hours. Once the "
"download has finished, the process cannot be cancelled."
msgstr ""
"アップグレードの取得とインストールには数時間かかることがあります。ダウンロー"
"ドが終了すると、アップグレードをキャンセルすることはできません。"

#. FIXME: this should go into DistUpgradeController
#: ../DistUpgrade/DistUpgradeView.py:348 ../UpdateManager/UpdateManager.py:503
msgid "Your system is up-to-date"
msgstr "システムは最新の状態です"

#: ../DistUpgrade/DistUpgradeView.py:349
msgid ""
"There are no upgrades available for your system. The upgrade will now be "
"canceled."
msgstr ""
"システムに適用可能なアップグレードはありません。アップグレードは中止されま"
"す。"

#: ../DistUpgrade/DistUpgradeView.py:362
msgid "Reboot required"
msgstr "再起動が必要です"

#: ../DistUpgrade/DistUpgradeView.py:363
msgid ""
"The upgrade is finished and a reboot is required. Do you want to do this now?"
msgstr ""
"アップグレードが終了しました。再起動が必要です。今すぐ自動で再起動しますか？"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:135
#: ../DistUpgrade/DistUpgradeFetcherCore.py:136
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:135
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:136
msgid "Could not run the upgrade tool"
msgstr "アップグレード・ツールを実行できません"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:136
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:136
msgid ""
"This is most likely a bug in the upgrade tool. Please report it as a bug"
msgstr "これはおそらくアップグレード・ツールのバグです。報告してください。"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:205
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:205
msgid "Upgrade tool signature"
msgstr "ツールの署名のアップグレード"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:208
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:208
msgid "Upgrade tool"
msgstr "ツールのアップグレード"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:237
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:237
msgid "Failed to fetch"
msgstr "取得に失敗しました"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:238
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:238
msgid "Fetching the upgrade failed. There may be a network problem. "
msgstr "アップグレードの取得に失敗しました。おそらくネットワークの問題です。 "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:242
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:242
msgid "Failed to extract"
msgstr "抽出に失敗しました"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:243
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:243
msgid ""
"Extracting the upgrade failed. There may be a problem with the network or "
"with the server. "
msgstr ""
"アップグレードの展開に失敗しました。おそらくネットワークまたはサーバの問題で"
"す。 "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:248
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:248
msgid "Verification failed"
msgstr "認証に失敗しました"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:249
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:249
msgid ""
"Verifying the upgrade failed.  There may be a problem with the network or "
"with the server. "
msgstr ""
"アップグレードの検証に失敗しました。ネットワーク接続もしくはサーバに問題があ"
"るかもしれません。 "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:254
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:254
msgid "Authentication failed"
msgstr "認証に失敗しました"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:255
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:255
msgid ""
"Authenticating the upgrade failed. There may be a problem with the network "
"or with the server. "
msgstr ""
"アップグレードの認証に失敗しました。おそらくネットワークまたはサーバの問題で"
"す。 "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:269
#: ../DistUpgrade/DistUpgradeFetcherCore.py:275
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:269
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:275
msgid "Can not run the upgrade"
msgstr "アップグレードを実行できません"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:270
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:270
msgid ""
"This usually is caused by a system were /tmp is mounted noexec. Please "
"remount without noexec and run the upgrade again."
msgstr ""
"これは主に /tmp が noexec マウントされているシステムで起こります。noexec オプ"
"ションなしで再マウントし、もう一度アップグレードを実行してください。"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:276
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:276
#, python-format
msgid "The error message is '%s'."
msgstr "エラーメッセージは'%s'です。"

#: ../DistUpgrade/DistUpgradeViewText.py:89
msgid ""
"Please report this as a bug and include the files /var/log/dist-upgrade/main."
"log and /var/log/dist-upgrade/apt.log in your report. The upgrade is now "
"aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"このことをバグとして、ファイル /var/log/dist-upgrade/main.log と /var/log/"
"dist-upgrade/apt.log をレポートに含めて報告してください。現在アップグレードは"
"中断されています。\n"
"元の sources.list は /etc/apt/sources.list.distUpgrade に保存されています。"

#: ../DistUpgrade/DistUpgradeViewText.py:113
msgid "Aborting"
msgstr "中断します"

#: ../DistUpgrade/DistUpgradeViewText.py:118
msgid "Demoted:\n"
msgstr "サポートレベルの格下げ:\n"

#: ../DistUpgrade/DistUpgradeViewText.py:150
#: ../DistUpgrade/DistUpgradeViewText.py:172
#: ../DistUpgrade/DistUpgradeViewText.py:179
msgid "Continue [yN] "
msgstr "続行する[yN] "

#: ../DistUpgrade/DistUpgradeViewText.py:150
#: ../DistUpgrade/DistUpgradeViewText.py:172
msgid "Details [d]"
msgstr "詳細 [d]"

#. TRANSLATORS: the "y" is "yes"
#. TRANSLATORS: first letter of a positive (yes) answer
#: ../DistUpgrade/DistUpgradeViewText.py:154
#: ../DistUpgrade/DistUpgradeViewText.py:182
msgid "y"
msgstr "y"

#. TRANSLATORS: the "n" is "no"
#. TRANSLATORS: first letter of a negative (no) answer
#: ../DistUpgrade/DistUpgradeViewText.py:157
#: ../DistUpgrade/DistUpgradeViewText.py:189
msgid "n"
msgstr "n"

#. TRANSLATORS: the "d" is "details"
#: ../DistUpgrade/DistUpgradeViewText.py:160
msgid "d"
msgstr "d"

#: ../DistUpgrade/DistUpgradeViewText.py:164
#, python-format
msgid "Remove: %s\n"
msgstr "削除: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:167
#, python-format
msgid "Install: %s\n"
msgstr "インストール: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:170
#, python-format
msgid "Upgrade: %s\n"
msgstr "アップグレード: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:186
msgid "Continue [Yn] "
msgstr "続ける [Yn] "

#: ../DistUpgrade/DistUpgradeViewText.py:207
msgid ""
"To finish the upgrade, a restart is required.\n"
"If you select 'y' the system will be restarted."
msgstr ""
"アップグレードを完了するには再起動が必要です。\n"
"'Y' を選択すると再起動します。"

#: ../DistUpgrade/DistUpgrade.ui.h:1
msgid "    "
msgstr "    "

#: ../DistUpgrade/DistUpgrade.ui.h:2
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly adviced to resume the upgrade."
msgstr ""
"<b><big>アップグレードをキャンセルしますか？</big></b>\n"
"\n"
"アップグレードをキャンセルすると、おそらくシステムは不安定な状態になります。"
"アップグレードを再開することを強くおすすめします。"

#: ../DistUpgrade/DistUpgrade.ui.h:5
msgid ""
"<b><big>Restart the system to complete the upgrade</big></b>\n"
"\n"
"Please save your work before continuing."
msgstr ""
"<b><big>アップグレードを完了するために、システムを再起動</big></b>\n"
"\n"
"先へ進む前に、他のアプリケーションで行っているすべての作業を保存してくださ"
"い。"

#: ../DistUpgrade/DistUpgrade.ui.h:8
msgid "<b><big>Start the upgrade?</big></b>"
msgstr "<b><big>アップグレードを開始しますか？</big></b>"

#: ../DistUpgrade/DistUpgrade.ui.h:9
msgid "<b><big>Upgrading Ubuntu to version 10.04 LTS</big></b>"
msgstr "<b><big>Ubuntu をバージョン 10.04 LTS へアップグレード</big></b>"

#: ../DistUpgrade/DistUpgrade.ui.h:12
msgid "Difference between the files"
msgstr "ファイル同士の差異"

#: ../DistUpgrade/DistUpgrade.ui.h:13
msgid "Distribution Upgrade"
msgstr "ディストリビューションのアップグレード"

#: ../DistUpgrade/DistUpgrade.ui.h:17
msgid "Restarting the computer"
msgstr "コンピュータの再起動"

#: ../DistUpgrade/DistUpgrade.ui.h:18
msgid "Setting new software channels"
msgstr "新しいソフトウェア・チャンネルを設定しています"

#: ../DistUpgrade/DistUpgrade.ui.h:19
msgid "Terminal"
msgstr "端末"

#: ../DistUpgrade/DistUpgrade.ui.h:20
msgid "_Cancel Upgrade"
msgstr "アップグレードをキャンセル(_C)"

#: ../DistUpgrade/DistUpgrade.ui.h:21
msgid "_Continue"
msgstr "続行する(_C)"

#: ../DistUpgrade/DistUpgrade.ui.h:23
msgid "_Replace"
msgstr "置き換える(_R)"

#: ../DistUpgrade/DistUpgrade.ui.h:24
msgid "_Report Bug"
msgstr "バグを報告する(_R)"

#: ../DistUpgrade/DistUpgrade.ui.h:26
msgid "_Resume Upgrade"
msgstr "アップグレードを再開(_R)"

#: ../DistUpgrade/DistUpgrade.ui.h:27
msgid "_Start Upgrade"
msgstr "アップグレードを開始(_S)"

#: ../UpdateManager/backend/InstallBackendSynaptic.py:42
msgid "Please wait, this can take some time."
msgstr "しばらくお待ちください。少し時間がかかります。"

#: ../UpdateManager/backend/InstallBackendSynaptic.py:44
msgid "Update is complete"
msgstr "アップデートが完了しました"

#: ../UpdateManager/DistUpgradeFetcher.py:85
#: ../UpdateManager/DistUpgradeFetcherKDE.py:103
msgid "Could not find the release notes"
msgstr "リリースノートが見つかりません"

#: ../UpdateManager/DistUpgradeFetcher.py:86
#: ../UpdateManager/DistUpgradeFetcherKDE.py:104
msgid "The server may be overloaded. "
msgstr "サーバに大きな負荷がかかっています。 "

#: ../UpdateManager/DistUpgradeFetcher.py:96
#: ../UpdateManager/DistUpgradeFetcherKDE.py:108
msgid "Could not download the release notes"
msgstr "リリースノートをダウンロードできません"

#: ../UpdateManager/DistUpgradeFetcher.py:97
#: ../UpdateManager/DistUpgradeFetcherKDE.py:109
msgid "Please check your internet connection."
msgstr "インターネット接続を確認してください。"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:62
#: ../UpdateManager/DistUpgradeFetcherKDE.py:85
msgid "Upgrade"
msgstr "アップグレード"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:89
#: ../data/glade/UpdateManager.ui.h:12
#: ../data/glade/UpgradePromptDialog.ui.h:4
msgid "Release Notes"
msgstr "リリースノート"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:128
#: ../UpdateManager/DistUpgradeFetcherKDE.py:141
#: ../UpdateManager/DistUpgradeFetcherKDE.py:143
msgid "Downloading additional package files..."
msgstr "追加パッケージのダウンロード..."

#: ../UpdateManager/DistUpgradeFetcherKDE.py:141
#, python-format
msgid "File %s of %s at %sB/s"
msgstr "ファイル %s / %s (%sB/s)"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:143
#, python-format
msgid "File %s of %s"
msgstr "ファイル %s / %s"

#: ../UpdateManager/ChangelogViewer.py:70
msgid "Open Link in Browser"
msgstr "リンクをブラウザで開く"

#: ../UpdateManager/ChangelogViewer.py:72
msgid "Copy Link to Clipboard"
msgstr "リンクをクリップボードにコピー"

#: ../UpdateManager/GtkProgress.py:116
#, python-format
msgid "Downloading file %(current)li of %(total)li with %(speed)s/s"
msgstr "ファイル %(current)li / %(total)li をダウンロード中 (%(speed)s/秒)"

#: ../UpdateManager/GtkProgress.py:121
#, python-format
msgid "Downloading file %(current)li of %(total)li"
msgstr "ファイル %(current)li / %(total)li をダウンロード中"

#: ../UpdateManager/UpdateManager.py:304
#, python-format
msgid "Version %s: \n"
msgstr "バージョン %s: \n"

#: ../UpdateManager/UpdateManager.py:361
msgid "Downloading list of changes..."
msgstr "変更点のリストを取得..."

#: ../UpdateManager/UpdateManager.py:401
msgid "_Uncheck All"
msgstr "すべてのチェックをはずす(_U)"

#: ../UpdateManager/UpdateManager.py:407
msgid "_Check All"
msgstr "すべてチェック(_C)"

#: ../UpdateManager/UpdateManager.py:451
#, python-format
msgid ""
"Download size: %s\n"
"%s selected."
msgstr ""
"ダウンロードサイズ: %s\n"
"%s 個が選択されています。"

#: ../UpdateManager/UpdateManager.py:456
msgid "Unknown download size"
msgstr "不明なダウンロードサイズ"

#: ../UpdateManager/UpdateManager.py:464
msgid ""
"It is unknown when the package information was updated last. Please try "
"clicking on the 'Check' button to update the information."
msgstr ""
"最後にパッケージ情報が更新された日時が不明です。「再チェック」ボタンをクリッ"
"クしてパッケージ情報を更新してください。"

#: ../UpdateManager/UpdateManager.py:473
#, python-format
msgid "The package information was last updated %s day ago."
msgid_plural "The package information was last updated %s days ago."
msgstr[0] "パッケージ情報は %s 日前に更新されました。"

#: ../UpdateManager/UpdateManager.py:477
#, python-format
msgid "The package information was last updated %s hour ago."
msgid_plural "The package information was last updated %s hours ago."
msgstr[0] "パッケージ情報は %s 時間前に更新されました。"

#: ../UpdateManager/UpdateManager.py:481
msgid "The package information was last updated less than one hour ago."
msgstr "パッケージ情報は1時間以内に更新されました。"

#: ../UpdateManager/UpdateManager.py:501 ../data/glade/UpdateManager.ui.h:23
msgid ""
"Software updates correct errors, eliminate security vulnerabilities and "
"provide new features."
msgstr ""
"ソフトウェアアップデートはエラーを修正し、セキュリティホールを取り除き、新し"
"い機能を提供します。"

#: ../UpdateManager/UpdateManager.py:520
msgid "Welcome to Ubuntu"
msgstr "Ubuntuへようこそ"

#: ../UpdateManager/UpdateManager.py:521
msgid ""
"These software updates have been issued since Ubuntu was released. If you "
"don't want to install them now, choose \"Update Manager\" from the "
"Administration Menu later."
msgstr ""
"これらのソフトウェアアップデートは、Ubuntu のリリース以降に公開されたもので"
"す。今すぐインストールしたくない場合は、後でシステム管理メニューから “アップ"
"デート・マネージャ” を選択してください。"

#: ../UpdateManager/UpdateManager.py:524
msgid "Software updates are available for this computer"
msgstr "このコンピュータで利用できるソフトウェアアップデートがあります"

#: ../UpdateManager/UpdateManager.py:525
msgid ""
"If you don't want to install them now, choose \"Update Manager\" from the "
"Administration menu later."
msgstr ""
"今すぐインストールしたくない場合は、後でシステム管理メニューから“アップデー"
"ト・マネージャ”を選択してください。"

#: ../UpdateManager/UpdateManager.py:574
#, python-format
msgid ""
"The upgrade needs a total of %s free space on disk '%s'. Please free at "
"least an additional %s of disk space on '%s'. Empty your trash and remove "
"temporary packages of former installations using 'sudo apt-get clean'."
msgstr ""
"アップグレードには全体で%sの空き領域がディスク'%s'に必要です。少なくとも%sの"
"領域を'%s'に確保してください。ゴミ箱を空にしたり、'sudo apt-get clean'を使っ"
"て過去にインストールした一時パッケージを削除してください。"

#: ../UpdateManager/UpdateManager.py:631
#: ../UpdateManagerHildon/UpdateManagerHildon.py:114
msgid "Reading package information"
msgstr "パッケージ情報を取得しています"

#: ../UpdateManager/UpdateManager.py:744
msgid "Could not initialize the package information"
msgstr "パッケージ情報を初期化できませんでした"

#: ../UpdateManager/UpdateManager.py:745
msgid ""
"An unresolvable problem occurred while initializing the package "
"information.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:\n"
msgstr ""
"パッケージ情報の初期化中に解決できない問題が発生しました。\n"
"\n"
"'update-manager'パッケージのバグとして、以下のエラーメッセージを含めてレポー"
"トしてください:\n"

#: ../UpdateManager/UpdateManager.py:767
msgid ""
"An unresolvable problem occurred while calculating the upgrade.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:"
msgstr ""
"アップグレードの計算中に解決できない問題が発生しました．\n"
"\n"
"'update-manager'パッケージのバグとして、以下のエラーメッセージを含めてレポー"
"トしてください:"

#: ../UpdateManager/UpdateManager.py:790
msgid " (New install)"
msgstr " (新規インストール)"

#. TRANSLATORS: the b stands for Bytes
#: ../UpdateManager/UpdateManager.py:794
#, python-format
msgid "(Size: %s)"
msgstr "(サイズ: %s)"

#: ../UpdateManager/UpdateManager.py:796
#, python-format
msgid "From version %(old_version)s to %(new_version)s"
msgstr "バージョン %(old_version)s から %(new_version)s　へ"

#: ../UpdateManager/UpdateManager.py:800
#, python-format
msgid "Version %s"
msgstr "バージョン %s"

#: ../UpdateManager/UpdateManager.py:813
msgid "Your Ubuntu release is not supported anymore"
msgstr "現在使っている Ubuntu のリリースはもうサポートされていません"

#: ../UpdateManager/UpdateManager.py:814
msgid ""
"You will not get any further security fixes or critical updates. Please "
"Upgrade to a later version of Ubuntu Linux."
msgstr ""
"これ以上セキュリティ修正や重要なアップデートはありません。新しいバージョンの "
"Ubuntu Linux にアップグレードしてください。"

#: ../UpdateManager/UpdateManager.py:821
msgid "Upgrade information"
msgstr "アップグレード情報"

#. print "on_button_dist_upgrade_clicked"
#: ../UpdateManager/UpdateManager.py:841 ../check-new-release-gtk:87
msgid "Downloading the release upgrade tool"
msgstr "リリースアップグレードツールのダウンロード"

#: ../UpdateManager/UpdateManager.py:848
#, python-format
msgid "<b>New Ubuntu release '%s' is available</b>"
msgstr "<b>Ubuntu の新しいリリース '%s' が利用可能です</b>"

#. we assert a clean cache
#: ../UpdateManager/UpdateManager.py:887
msgid "Software index is broken"
msgstr "ソフトウェア・インデックスが壊れています"

#: ../UpdateManager/UpdateManager.py:888
msgid ""
"It is impossible to install or remove any software. Please use the package "
"manager \"Synaptic\" or run \"sudo apt-get install -f\" in a terminal to fix "
"this issue at first."
msgstr ""
"どのソフトウェアもインストールまたは削除することができません。 まずこの問題を"
"解決するために \"Synapticパッケージ・マネージャ\" を起動するか、  \"sudo apt-"
"get install -f\" コマンドをターミナルで実行してください。"

#: ../UpdateManagerHildon/UpdateManagerHildon.py:136
msgid "Downloading Package Information"
msgstr "パッケージ情報をダウンロードしています"

#: ../UpdateManagerHildon/UpdateManagerHildon.py:137
msgid ""
"The repositories are being checked for new, removed, or updated software "
"packages"
msgstr ""
"新規追加、削除または更新されたパッケージがリポジトリにあるかどうかチェックし"
"ています"

#: ../UpdateManagerHildon/UpdateManagerHildon.py:145
msgid "Downloading Package Updates"
msgstr "パッケージのアップデータをダウンロードしています"

#: ../UpdateManagerHildon/UpdateManagerHildon.py:146
msgid ""
"The selected package updates are being downloaded and installed on the system"
msgstr ""
"選択されたパッケージのアップデータのダウンロードとインストールをしています"

#: ../UpdateManagerHildon/UpdateManagerHildon.py:152
msgid "run_synaptic called with unknown action"
msgstr "run_synaptic が不明なアクションとともに呼び出されました"

#: ../UpdateManagerText/UpdateManagerText.py:26
msgid "Cancel"
msgstr "キャンセル"

#: ../UpdateManagerText/UpdateManagerText.py:27
msgid "Install"
msgstr "インストール"

#: ../UpdateManagerText/UpdateManagerText.py:45
msgid "Building Updates List"
msgstr "アップデートリストを構成しています"

#: ../UpdateManagerText/UpdateManagerText.py:48
msgid ""
"\n"
"A normal upgrade can not be calculated, please run: \n"
"  sudo apt-get dist-upgrade\n"
"\n"
"\n"
"This can be caused by:\n"
" * A previous upgrade which didn't complete\n"
" * Problems with some of the installed software\n"
" * Unofficial software packages not provided by Ubuntu\n"
" * Normal changes of a pre-release version of Ubuntu"
msgstr ""
"\n"
"通常のアップグレードの見積もりが行えませんでした。以下を実行してください: \n"
"  sudo apt-get dist-upgrade\n"
"\n"
"\n"
"以下の原因が考えられます:\n"
" * 前回のアップグレードが完了していなかった。\n"
" * インストールしたソフトウェアのどれかに問題がある。\n"
" * Ubuntu が提供していない、非公式なパッケージを利用している。\n"
" * Ubuntu のリリース前バージョンにおける、通常の変更。"

#: ../UpdateManagerText/UpdateManagerText.py:117
msgid "Downloading changelog"
msgstr "変更履歴をダウンロードしています"

#: ../UpdateManager/Core/MyCache.py:124
#, python-format
msgid "Other updates (%s)"
msgstr "その他のアップデート (%s)"

#: ../UpdateManager/Core/MyCache.py:246
#, python-format
msgid ""
"Changes for the versions:\n"
"%s\n"
"%s\n"
"\n"
msgstr ""
"このバージョンでの変更点：\n"
"%s\n"
"%s\n"
"\n"

#: ../UpdateManager/Core/MyCache.py:248
msgid "This change is not coming from a source that supports changelogs."
msgstr "この変更は変更履歴をサポートするソースからのものではありません．"

#: ../UpdateManager/Core/MyCache.py:256
#, python-format
msgid ""
"The changelog does not contain any relevant changes.\n"
"\n"
"Please use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"until the changes become available or try again later."
msgstr ""
"変更履歴には関連する変更点がありません。\n"
"\n"
"変更内容が表示されるようになるまで、http://launchpad.net/ubuntu/+source/%s/%"
"s/+changelog\n"
"を利用するか、後ほど再び試してください。"

#: ../UpdateManager/Core/MyCache.py:261
#, python-format
msgid ""
"The list of changes is not available yet.\n"
"\n"
"Please use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"until the changes become available or try again later."
msgstr ""
"変更点のリストはまだ利用できません。\n"
"\n"
"変更内容が表示されるようになるまで、http://launchpad.net/ubuntu/+source/%s/%"
"s/+changelog\n"
"を利用するか、後ほど再び試してください。"

#: ../UpdateManager/Core/MyCache.py:267
msgid ""
"Failed to download the list of changes. \n"
"Please check your Internet connection."
msgstr ""
"変更内容のダウンロードに失敗しました。\n"
"インターネットに接続されているか確認してください。"

#: ../UpdateManager/Core/UpdateList.py:50
msgid "Failed to detect distribution"
msgstr "ディストリビューションの検出に失敗しました"

#: ../UpdateManager/Core/UpdateList.py:51
#, python-format
msgid "A error '%s' occurred while checking what system you are using."
msgstr "使用しているシステムを確認している際に、エラー '%s' が起きました。"

#: ../UpdateManager/Core/UpdateList.py:62
msgid "Important security updates"
msgstr "重要なセキュリティアップデート"

#: ../UpdateManager/Core/UpdateList.py:63
msgid "Recommended updates"
msgstr "推奨アップデート"

#: ../UpdateManager/Core/UpdateList.py:64
msgid "Proposed updates"
msgstr "「Proposed」（テスト版）アップデート"

#: ../UpdateManager/Core/UpdateList.py:65
msgid "Backports"
msgstr "バックポート"

#: ../UpdateManager/Core/UpdateList.py:66
msgid "Distribution updates"
msgstr "ディストリビューションのアップデート"

#: ../UpdateManager/Core/UpdateList.py:71
msgid "Other updates"
msgstr "その他のアップデート"

#: ../UpdateManager/Core/UpdateList.py:80
msgid "Previous selected"
msgstr "以前に選択したもの"

#: ../data/glade/UpdateManager.ui.h:1
msgid ""
"<b><big>You must check for updates manually</big></b>\n"
"\n"
"Your system does not check for updates automatically. You can configure this "
"behavior in <i>Software Sources</i> on the <i>Updates</i> tab."
msgstr ""
"<b><big>アップデートの情報を手動でチェックする必要があります</big></b>\n"
"\n"
"アップデート情報を自動チェックしない設定になっています。この動作の変更は、<i>"
"ソフトウェア・ソース</i>の<i>インターネットアップデート</i>タブで行います。"

#: ../data/glade/UpdateManager.ui.h:4
msgid "<big><b>Not all updates can be installed</b></big>"
msgstr "<big><b>一部のアップデータだけがインストール可能です</b></big>"

#: ../data/glade/UpdateManager.ui.h:5
msgid "<big><b>Running on battery</b></big>"
msgstr "<big><b>バッテリーで動作中です</b></big>"

#: ../data/glade/UpdateManager.ui.h:6
msgid "<big><b>Starting Update Manager</b></big>"
msgstr "<big><b>アップデート・マネージャを起動しています</b></big>"

#: ../data/glade/UpdateManager.ui.h:7
msgid "Changes"
msgstr "変更箇所"

#: ../data/glade/UpdateManager.ui.h:8
msgid "Chec_k"
msgstr "再チェック(_K)"

#: ../data/glade/UpdateManager.ui.h:9
msgid "Co_ntinue"
msgstr "続行(_N)"

#: ../data/glade/UpdateManager.ui.h:10
msgid "Description"
msgstr "詳細"

#: ../data/glade/UpdateManager.ui.h:11
msgid "Description of update"
msgstr "アップデートの詳細"

#: ../data/glade/UpdateManager.ui.h:13
msgid "Restart _Later"
msgstr "あとで再起動(_L)"

#: ../data/glade/UpdateManager.ui.h:14
msgid ""
"Run a partial upgrade, to install as many updates as possible. \n"
"\n"
"This can be caused by:\n"
" * A previous upgrade which didn't complete\n"
" * Problems with some of the installed software\n"
" * Unofficial software packages not provided by Ubuntu\n"
" * Normal changes of a pre-release version of Ubuntu"
msgstr ""
"できる限り多くのアップデートをインストールするため、部分アップグレードを実行"
"します。 \n"
"\n"
"以下の原因が考えられます:\n"
"* 以前のアップグレードが完了していなかった。\n"
"* インストールしたソフトウェアのどれかに問題がある。\n"
"* Ubuntu が提供していない、非公式なパッケージを使用している。\n"
"* 開発版 Ubuntu を利用している（開発版における通常の変更）。"

#: ../data/glade/UpdateManager.ui.h:21
msgid "Settings..."
msgstr "設定..."

#: ../data/glade/UpdateManager.ui.h:22
#: ../data/glade/UpgradePromptDialog.ui.h:5
msgid "Show progress of individual files"
msgstr "個別のファイルの進捗を表示"

#: ../data/glade/UpdateManager.ui.h:24
msgid ""
"The computer needs to restart to finish installing updates. Please save your "
"work before continuing."
msgstr ""
"アップデートのインストールを完了するためにはコンピュータの再起動が必要です。"
"インストールを続行する前に現在行っている作業の保存をして下さい。"

#: ../data/glade/UpdateManager.ui.h:25
msgid "U_pgrade"
msgstr "アップグレード(_P)"

#: ../data/glade/UpdateManager.ui.h:26 ../data/update-manager.desktop.in.h:3
#: ../data/update-manager-hildon.desktop.in.h:3
msgid "Update Manager"
msgstr "アップデート・マネージャ"

#: ../data/glade/UpdateManager.ui.h:27
msgid "Your system is running on battery. Are you sure you want to continue?"
msgstr ""
"あなたのシステムはバッテリーで動作中です。このまま処理を継続してよろしいです"
"か？"

#: ../data/glade/UpdateManager.ui.h:28
msgid "_Hide this information in the future"
msgstr "今後この情報を表示しない(_H)"

#: ../data/glade/UpdateManager.ui.h:29
msgid "_Install Updates"
msgstr "アップデートをインストール(_I)"

#: ../data/glade/UpdateManager.ui.h:30
msgid "_Partial Upgrade"
msgstr "部分的なアップグレード(_P)"

#: ../data/glade/UpdateManager.ui.h:32
msgid "_Upgrade"
msgstr "アップグレード(_U)"

#: ../data/glade/UpdateManager.ui.h:33
msgid "updates"
msgstr "アップデート"

#: ../data/glade/UpgradePromptDialog.ui.h:1
msgid "<b>A new version of Ubuntu is available. Would you like to upgrade?</b>"
msgstr ""
"<b>新しいバージョンの Ubuntu が利用可能です。アップグレードしますか?</b>"

#: ../data/glade/UpgradePromptDialog.ui.h:2
msgid "Ask Me Later"
msgstr "次回にたずねる"

#: ../data/glade/UpgradePromptDialog.ui.h:3
msgid "Don't Upgrade"
msgstr "アップグレードしない"

#: ../data/glade/UpgradePromptDialog.ui.h:6
msgid "Yes, Upgrade Now"
msgstr "今すぐアップグレードする"

#: ../data/glade/UpgradePromptDialog.ui.h:7
msgid ""
"You can upgrade at a later time by opening Update Manager and click on "
"\"Upgrade\"."
msgstr ""
"後でアップデート・マネージャを開いて \"アップグレード\" をクリックすればアッ"
"プグレードできます。"

#: ../data/glade/UpgradePromptDialog.ui.h:8
msgid "You have declined to upgrade to the new Ubuntu"
msgstr ""

#: ../data/update-manager.desktop.in.h:1
#: ../data/update-manager-hildon.desktop.in.h:1
msgid "Show and install available updates"
msgstr "利用できるアップデートの閲覧・インストール"

#: ../data/update-manager.desktop.in.h:2
#: ../data/update-manager-hildon.desktop.in.h:2
msgid "Software Updates"
msgstr "ソフトウェアのアップデート"

#: ../data/update-manager.schemas.in.h:1
msgid "*deprecated* Check for new distribution releases"
msgstr "*廃止予定* 新しいディストリビューションのリリースをチェックする"

#: ../data/update-manager.schemas.in.h:2
msgid "Auto close the install window after successful install"
msgstr "インストールに成功したら、インストールウインドウを自動で閉じる"

#: ../data/update-manager.schemas.in.h:3
msgid "First run welcome message"
msgstr "最初に「ようこそ」メッセージを実行する"

#: ../data/update-manager.schemas.in.h:4
msgid ""
"If automatic checking for updates is disabled, you have to reload the "
"channel list manually. This option allows to hide the reminder shown in this "
"case."
msgstr ""
"アップデートの自動チェックを無効にすると、チャンネルリストを手動で再読み込み"
"しなければなりません。このオプションを使うと、こういった場合にリマインダの表"
"示を隠すことができます。"

#: ../data/update-manager.schemas.in.h:5
msgid "If this key is set a first run welcome message will be presented."
msgstr ""
"このキーが設定されると、最初の起動時に「ようこそ」メッセージが表示されます。"

#: ../data/update-manager.schemas.in.h:6
msgid ""
"If this key is set the install window will be automatically closed on "
"successful installation."
msgstr ""
"このキーを設定すると、インストールが成功したときにウィンドウを自動的に閉じま"
"す。"

#: ../data/update-manager.schemas.in.h:7
msgid ""
"If this key is set the main update list window will show version information "
"(from version to version)."
msgstr ""
"オンにすると、アップデートの一覧ウィンドウで、バージョンの情報（どのバージョ"
"ンからどのバージョンへアップデートするか）を表示します。"

#: ../data/update-manager.schemas.in.h:8
msgid "Remind to reload the channel list"
msgstr "チャンネルリストの再読み込みを後で再表示する"

#: ../data/update-manager.schemas.in.h:9
msgid "Show details of an update"
msgstr "アップデートの詳細を表示"

#: ../data/update-manager.schemas.in.h:10
msgid "Show version in update list"
msgstr "アップデートされるバージョンを表示"

#: ../data/update-manager.schemas.in.h:11
msgid "Stores the size of the update-manager dialog"
msgstr "アップデート・マネージャのウインドウサイズを記憶する"

#: ../data/update-manager.schemas.in.h:12
msgid ""
"Stores the state of the expander that contains the list of changes and the "
"description"
msgstr "変更内容と詳細表示ボタンの状態を記憶します。"

#: ../data/update-manager.schemas.in.h:13
msgid "The window size"
msgstr "ウィンドウサイズ"

#: ../data/update-manager.schemas.in.h:14
msgid ""
"This key is deprecated in favor of the file /etc/update-manager/release-"
"upgrades Check automatically if a new version of the current distribution is "
"available and offer to upgrade (if possible)."
msgstr ""
"/etc/update-manager/release-upgrades の状態にしたがって自動的に設定される、廃"
"止予定のキーです。もしディストリビューションの新しいバージョンが利用可能に"
"なっていれば、アップグレードするように促します。"

#: ../data/update-manager.schemas.in.h:15
msgid ""
"This will permanently hide the new release prompt from check-new-release-"
"gtk. Note that the small button in the main update-manager UI will still be "
"there."
msgstr ""

#: ../data/update-manager.schemas.in.h:16
msgid "make check-new-release-gtk ignore a given new release"
msgstr ""

#: ../update-manager:56 ../do-release-upgrade:33
msgid "Show version and exit"
msgstr "バージョンを表示して終了"

#: ../update-manager:59
msgid "Directory that contains the data files"
msgstr "データファイルの含まれるディレクトリ"

#: ../update-manager:62
msgid "Check if a new Ubuntu release is available"
msgstr "新しい Ubuntu のリリースが利用可能かどうかチェックする"

#: ../update-manager:65 ../do-release-upgrade:36 ../check-new-release:27
#: ../check-new-release-gtk:149
msgid "Check if upgrading to the latest devel release is possible"
msgstr "最新の開発リリースへのアップデートが利用可能かどうかチェックする"

#: ../update-manager:69
msgid "Upgrade using the latest proposed version of the release upgrader"
msgstr ""
"リリースアップグレードが提案する最新のバージョンを使ってアップグレードを行う"

#: ../update-manager:76
msgid "Do not focus on map when starting"
msgstr "起動時にウィンドウに入力フォーカスを当てない"

#: ../update-manager:79
msgid "Try to run a dist-upgrade"
msgstr "dist-upgradeを実行する"

#: ../update-manager:83 ../do-release-upgrade:52
msgid "Test upgrade with a sandbox aufs overlay"
msgstr "aufsオーバレイを実験環境に用いてのテストアップグレード"

#: ../update-manager:103
msgid "Running partial upgrade"
msgstr "部分的なアップグレードを実行"

#: ../do-release-upgrade:40 ../check-new-release:31
#: ../check-new-release-gtk:153
msgid ""
"Try upgrading to the latest release using the upgrader from $distro-proposed"
msgstr ""
"アップグレードソフトウェアを使って $distro-proposed から最新のリリースへの"
"アップグレードを試す"

#: ../do-release-upgrade:44
msgid ""
"Run in a special upgrade mode.\n"
"Currently 'desktop' for regular upgrades of a desktop system and 'server' "
"for server systems are supported."
msgstr ""
"特別なアップグレードモードで実行する。\n"
"現在、デスクトップシステムの標準的なアップグレードを行う 'desktop' オプション"
"と、サーバシステム向けの 'server' オプションがサポートされています。"

#: ../do-release-upgrade:50
msgid "Run the specified frontend"
msgstr "特定のフロントエンドで実行"

#: ../do-release-upgrade:55
msgid ""
"Check only if a new distribution release is available and report the result "
"via the exit code"
msgstr ""

#: ../do-release-upgrade:69
msgid "Checking for a new ubuntu release"
msgstr "新しいUbuntuのリリースをチェックする"

#: ../do-release-upgrade:79
msgid "No new release found"
msgstr "新しくリリースされたものはありません"

#: ../do-release-upgrade:85 ../check-new-release:56
#, c-format
msgid "New release '%s' available."
msgstr "新しいリリース '%s' が利用可能になっています。"

#: ../do-release-upgrade:86 ../check-new-release:57
msgid "Run 'do-release-upgrade' to upgrade to it."
msgstr "'do-release-upgrade' を実行してアップグレードしてください"

#: ../check-new-release:35
#, c-format
msgid ""
"Do not output anything, just return %s if there is a new release and %s if "
"there is none."
msgstr ""
"何も出力せずに、新しいリリースがあるなら%sを、なければ%sを終了ステータスとし"
"て返します。"

#: ../check-new-release-gtk:67
msgid "Ubuntu %(version)s Upgrade Available"
msgstr "Ubuntu %(version) のアップグレードが利用可能です"

#: ../check-new-release-gtk:103
#, c-format
msgid "You have declined the upgrade to Ubuntu %s"
msgstr ""

#: ../Janitor/computerjanitor/exc.py:30
#, python-format
msgid "Unimplemented method: %s"
msgstr "未実装のメソッド： %s"

#: ../Janitor/computerjanitor/file_cruft.py:46
msgid "A file on disk"
msgstr "ディスクにあるファイル"

#: ../Janitor/computerjanitor/package_cruft.py:45
msgid ".deb package"
msgstr ".deb パッケージ"

#: ../Janitor/computerjanitor/missing_package_cruft.py:33
msgid "Install missing package."
msgstr "見つからないパッケージをインストール"

#: ../Janitor/computerjanitor/missing_package_cruft.py:42
#, python-format
msgid "Package %s should be installed."
msgstr "パッケージ %s はインストールされている必要があります。"

#. pragma: no cover
#: ../Janitor/plugins/dpkg_status_plugin.py:36
#, python-format
msgid "%i obsolete entries in the status file"
msgstr "ステータスファイル内に %i 個の廃止されたエントリがあります。"

#: ../Janitor/plugins/dpkg_status_plugin.py:39
msgid "Obsolete entries in dpkg status"
msgstr "dpkgステータス内に廃止されたエントリがあります"

#. pragma: no cover
#: ../Janitor/plugins/dpkg_status_plugin.py:42
msgid "Obsolete dpkg status entries"
msgstr "廃止されたdpkgステータスエントリ"

#: ../Janitor/plugins/kdelibs4to5_plugin.py:39
msgid ""
"When upgrading, if kdelibs4-dev is installed, kdelibs5-dev needs to be "
"installed. See bugs.launchpad.net, bug #279621 for details."
msgstr ""
"アップグレードを行う場合、kdelibs4-dev がインストールされているなら、"
"kdelibs5-dev をインストールする必要があります。詳細は bugs.launchpad.net の "
"bug #279621 を参照してください。"

#: ../Janitor/plugins/langpack_manual_plugin.py:34
#, python-format
msgid "%s needs to be marked as manually installed."
msgstr "%s は手動インストール済みとマークされている必要があります。"

#: ../Janitor/plugins/remove_lilo_plugin.py:28
msgid "Remove lilo since grub is also installed.(See bug #314004 for details.)"
msgstr ""
"grub もインストールされているので lilo を削除します。(詳細は bug #314004 を参"
"照してください。)"
