# Ubuntu-ja translation of update-manager.
# Copyright (C) 2006 THE update-manager'S COPYRIGHT HOLDER
# This file is distributed under the same license as the update-manager package.
# Ikuya Awashiro <ikuya@fruitsbasket.info>, 2006.
# Hiroyuki Ikezoe <ikezoe@good-day.co.jp>, 2005
#
#
msgid ""
msgstr ""
"Project-Id-Version: update-manager 0.42.4\n"
"Report-Msgid-Bugs-To: sebastian.heinlein@web.de\n"
"POT-Creation-Date: 2013-05-22 21:30+0100\n"
"PO-Revision-Date: 2013-05-23 02:44+0000\n"
"Last-Translator: Mitsuya Shibata <mty.shibata@gmail.com>\n"
"Language-Team: Ubuntu Japanese Team <ubuntu-ja-users@freeml.com>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Launchpad-Export-Date: 2014-04-23 06:51+0000\n"
"X-Generator: Launchpad (build 16985)\n"
"Language: \n"

#. TRANSLATORS: %s is a country
#: ../DistUpgrade/distro.py:211 ../DistUpgrade/distro.py:441
#, python-format
msgid "Server for %s"
msgstr "%s にあるサーバー"

#. More than one server is used. Since we don't handle this case
#. in the user interface we set "custom servers" to true and
#. append a list of all used servers
#: ../DistUpgrade/distro.py:229 ../DistUpgrade/distro.py:235
#: ../DistUpgrade/distro.py:251
msgid "Main server"
msgstr "メインサーバー"

#: ../DistUpgrade/distro.py:255
msgid "Custom servers"
msgstr "カスタムサーバー群"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:142
msgid "Could not calculate sources.list entry"
msgstr "sources.listのエントリーから作業内容を見積もれません"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:251
msgid ""
"Unable to locate any package files, perhaps this is not a Ubuntu Disc or the "
"wrong architecture?"
msgstr "パッケージファイルが見つかりません。UbuntuのCDではないか、異なるアーキテクチャー向けのCDかもしれません。"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:294
msgid "Failed to add the CD"
msgstr "CDの追加に失敗しました"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:295
#, python-format
msgid ""
"There was a error adding the CD, the upgrade will abort. Please report this "
"as a bug if this is a valid Ubuntu CD.\n"
"\n"
"The error message was:\n"
"'%s'"
msgstr ""
"CD をリソースとして追加できなかったため、アップグレードは終了されます。この CD が正規の Ubuntu CD "
"の場合は、このことをバグとして報告してください。\n"
"\n"
"エラーメッセージ：\n"
"'%s'"

#: ../DistUpgrade/DistUpgradeCache.py:152
msgid "Remove package in bad state"
msgid_plural "Remove packages in bad state"
msgstr[0] "壊れた状態のパッケージを削除する"

#: ../DistUpgrade/DistUpgradeCache.py:155
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Do you want to remove this package now "
"to continue?"
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archives can be found for them. Do you want to remove these packages "
"now to continue?"
msgstr[0] ""
"パッケージ '%s' は 矛盾した状態にあり再インストールが必要ですが、そのためのアーカイブを見つけることができません。 "
"このパッケージを削除して先に進めますか？"

#. FIXME: not ideal error message, but we just reuse a
#. existing one here to avoid a new string
#: ../DistUpgrade/DistUpgradeCache.py:256
msgid "The server may be overloaded"
msgstr "サーバーが過負荷状態にある可能性があります"

#: ../DistUpgrade/DistUpgradeCache.py:369
msgid "Broken packages"
msgstr "壊れたパッケージ"

#: ../DistUpgrade/DistUpgradeCache.py:370
msgid ""
"Your system contains broken packages that couldn't be fixed with this "
"software. Please fix them first using synaptic or apt-get before proceeding."
msgstr ""
"システムにはこのソフトウェアでは修復できない壊れたパッケージが含まれています。 Synaptic や apt-get を使って最初に修正してください。"

#. FIXME: change the text to something more useful
#: ../DistUpgrade/DistUpgradeCache.py:693
#, python-format
msgid ""
"An unresolvable problem occurred while calculating the upgrade:\n"
"%s\n"
"\n"
" This can be caused by:\n"
" * Upgrading to a pre-release version of Ubuntu\n"
" * Running the current pre-release version of Ubuntu\n"
" * Unofficial software packages not provided by Ubuntu\n"
"\n"
msgstr ""
"アップグレードの見積もり中に解決できない問題が発生しました:\n"
"%s\n"
"\n"
" 以下の原因が考えられます:\n"
" * Ubuntu のリリース前バージョンへアップグレードしようとしている。\n"
" * Ubuntu のリリース前バージョンを使っている。\n"
" * Ubuntu が提供していない、非公式なパッケージを利用している。\n"
"\n"

#: ../DistUpgrade/DistUpgradeCache.py:648
msgid "This is most likely a transient problem, please try again later."
msgstr "これは一時的な問題のようです。後でもう一度試してください。"

#: ../DistUpgrade/DistUpgradeCache.py:651
msgid ""
"If none of this applies, then please report this bug using the command "
"'ubuntu-bug ubuntu-release-upgrader-core' in a terminal."
msgstr ""
"いずれかにも当てはまらない場合には、端末上から 'ubuntu-bug ubuntu-release-upgrader-core' "
"を実行してこのバグを報告してください。"

#: ../DistUpgrade/DistUpgradeCache.py:656
msgid "Could not calculate the upgrade"
msgstr "アップグレード作業を見積もれません"

#: ../DistUpgrade/DistUpgradeCache.py:707
msgid "Error authenticating some packages"
msgstr "パッケージの認証において、エラーがありました"

#: ../DistUpgrade/DistUpgradeCache.py:708
msgid ""
"It was not possible to authenticate some packages. This may be a transient "
"network problem. You may want to try again later. See below for a list of "
"unauthenticated packages."
msgstr ""
"いくつかのパッケージが認証できませんでした。これは一時的なネットワークの問題かもしれません。あとで再び試してみてください。以下に認証できなかったパッケージ"
"のリストが表示されます。"

#: ../DistUpgrade/DistUpgradeCache.py:728
#, python-format
msgid ""
"The package '%s' is marked for removal but it is in the removal blacklist."
msgstr "パッケージ'%s'は「削除」と指定されていますが、削除ブラックリストに入っています。"

#: ../DistUpgrade/DistUpgradeCache.py:732
#, python-format
msgid "The essential package '%s' is marked for removal."
msgstr "必須パッケージ'%s'に「削除」マークがついています。"

#: ../DistUpgrade/DistUpgradeCache.py:741
#, python-format
msgid "Trying to install blacklisted version '%s'"
msgstr "ブラックリストに入っているバージョン '%s' をインストールしようとしています"

#: ../DistUpgrade/DistUpgradeCache.py:859
#, python-format
msgid "Can't install '%s'"
msgstr "'%s'をインストールすることができません。"

#: ../DistUpgrade/DistUpgradeCache.py:860
msgid ""
"It was impossible to install a required package. Please report this as a bug "
"using 'ubuntu-bug ubuntu-release-upgrader-core' in a terminal."
msgstr ""
"必要なパッケージをインストールできませんでした。端末上から 'ubuntu-bug ubuntu-release-upgrader-core' "
"を実行し、これをバグとして報告してください。"

#. FIXME: provide a list
#: ../DistUpgrade/DistUpgradeCache.py:871
msgid "Can't guess meta-package"
msgstr "メタパッケージを推測できません"

#: ../DistUpgrade/DistUpgradeCache.py:872
msgid ""
"Your system does not contain a ubuntu-desktop, kubuntu-desktop, xubuntu-"
"desktop or edubuntu-desktop package and it was not possible to detect which "
"version of Ubuntu you are running.\n"
" Please install one of the packages above first using synaptic or apt-get "
"before proceeding."
msgstr ""
"システムに ubuntu-desktop, kubuntu-desktop, xubuntu-desktop, もしくはedubuntu-desktop "
"パッケージが含まれていません。このため、実行している ubuntu のバージョンが検出できません。 \n"
" 続ける前に、Synaptic や apt-get を使用して、まずは上記のパッケージのうちのいずれかをインストールしてください。"

#: ../DistUpgrade/DistUpgradeController.py:126
msgid "Reading cache"
msgstr "キャッシュを読み込み中"

#: ../DistUpgrade/DistUpgradeController.py:230
msgid "Unable to get exclusive lock"
msgstr "排他的なロックができません"

#: ../DistUpgrade/DistUpgradeController.py:231
msgid ""
"This usually means that another package management application (like apt-get "
"or aptitude) already running. Please close that application first."
msgstr ""
"パッケージマネージャーは一度にひとつしか起動できません。apt-getやaptitudeなどのような、他のパッケージマネージャーを終了してください。"

#: ../DistUpgrade/DistUpgradeController.py:289
msgid "Upgrading over remote connection not supported"
msgstr "リモート接続経由でのアップグレードはサポートされていません"

#: ../DistUpgrade/DistUpgradeController.py:290
msgid ""
"You are running the upgrade over a remote ssh connection with a frontend "
"that does not support this. Please try a text mode upgrade with 'do-release-"
"upgrade'.\n"
"\n"
"The upgrade will abort now. Please try without ssh."
msgstr ""
"このアップグレード処理は、リモートSSH経由で実行されたフロントエンドGUIから実行されているようです。\n"
"このツールはそうした処理をサポートしていません。\n"
"\n"
"もしリモートからのアップグレードを望むなら、テキストモードでのアップグレード 'do-release-upgrade' を試してみてください。\n"
"\n"
"アップグレードは中断されます。SSHを経由しない起動方法で実行してください。"

#: ../DistUpgrade/DistUpgradeController.py:304
msgid "Continue running under SSH?"
msgstr "SSH経由で実行していますが、続けますか？"

#: ../DistUpgrade/DistUpgradeController.py:305
#, python-format
msgid ""
"This session appears to be running under ssh. It is not recommended to "
"perform a upgrade over ssh currently because in case of failure it is harder "
"to recover.\n"
"\n"
"If you continue, an additional ssh daemon will be started at port '%s'.\n"
"Do you want to continue?"
msgstr ""
"このセッションはSSH上で実行されているようです。アップグレードをSSH越しに行うことは推奨されません。アップグレードに失敗した時の復元が困難になるからで"
"す。\n"
"\n"
"続行する場合、追加のSSHデーモンをポート '%s' で起動します。\n"
"本当に作業を進めてよろしいですか？"

#: ../DistUpgrade/DistUpgradeController.py:319
msgid "Starting additional sshd"
msgstr "予備のsshdを開始します"

#: ../DistUpgrade/DistUpgradeController.py:320
#, python-format
msgid ""
"To make recovery in case of failure easier, an additional sshd will be "
"started on port '%s'. If anything goes wrong with the running ssh you can "
"still connect to the additional one.\n"
msgstr ""
"障害が起こったときに復旧しやすくするため、ポート '%s' でもう一つの sshd "
"を開始します。現在実行中のsshにおかしなことが起きても、もう一方のポートに接続することができます。\n"

#: ../DistUpgrade/DistUpgradeController.py:328
#, python-format
msgid ""
"If you run a firewall, you may need to temporarily open this port. As this "
"is potentially dangerous it's not done automatically. You can open the port "
"with e.g.:\n"
"'%s'"
msgstr ""
"ファイアウォールを実行している場合、このポートを一時的に開く必要があります。この操作は、潜在的な危険があるため自動的には行われません。以下の例のようにして"
"ポートを開けます:\n"
"'%s'"

#: ../DistUpgrade/DistUpgradeController.py:400
#: ../DistUpgrade/DistUpgradeController.py:445
msgid "Can not upgrade"
msgstr "アップグレードできません"

#: ../DistUpgrade/DistUpgradeController.py:401
#, python-format
msgid "An upgrade from '%s' to '%s' is not supported with this tool."
msgstr "'%s' から '%s' へのアップグレードは、このツールではサポートされていません。"

#: ../DistUpgrade/DistUpgradeController.py:410
msgid "Sandbox setup failed"
msgstr "サンドボックス環境のセットアップに失敗しました"

#: ../DistUpgrade/DistUpgradeController.py:411
msgid "It was not possible to create the sandbox environment."
msgstr "サンドボックス環境を構築することができませんでした。"

#: ../DistUpgrade/DistUpgradeController.py:417
msgid "Sandbox mode"
msgstr "サンドボックスモード"

#: ../DistUpgrade/DistUpgradeController.py:418
#, python-format
msgid ""
"This upgrade is running in sandbox (test) mode. All changes are written to "
"'%s' and will be lost on the next reboot.\n"
"\n"
"*No* changes written to a system directory from now until the next reboot "
"are permanent."
msgstr ""
"このアップグレードはサンドボックス(テスト)モードで実行中です。すべての変更は '%s' に書きこまれ、次に再起動したときに破棄されます。\n"
"\n"
"現時点から次に再起動するまでの間にシステムディレクトリに書き込まれた変更は、破棄されます。"

#: ../DistUpgrade/DistUpgradeController.py:446
msgid ""
"Your python install is corrupted. Please fix the '/usr/bin/python' symlink."
msgstr "インストールされたPythonが破損しています。シンボリックリンク'/usr/bin/python'を修正してください。"

#: ../DistUpgrade/DistUpgradeController.py:472
msgid "Package 'debsig-verify' is installed"
msgstr "'debsig-verify'パッケージがインストールされています"

#: ../DistUpgrade/DistUpgradeController.py:473
msgid ""
"The upgrade can not continue with that package installed.\n"
"Please remove it with synaptic or 'apt-get remove debsig-verify' first and "
"run the upgrade again."
msgstr ""
"'debsig-verify'パッケージがインストールされていると、アップグレードを継続することができません。\n"
"Synapticパッケージマネージャーか 'apt-get remove debsig-verify' "
"で削除した後で、再度アップグレードを実行してください。"

#: ../DistUpgrade/DistUpgradeController.py:485
#, python-format
msgid "Can not write to '%s'"
msgstr "'%s' に書き込みできません"

#: ../DistUpgrade/DistUpgradeController.py:486
#, python-format
msgid ""
"Its not possible to write to the system directory '%s' on your system. The "
"upgrade can not continue.\n"
"Please make sure that the system directory is writable."
msgstr ""
"システムディレクトリ '%s' に書き込みできないため、アップグレードを続行できません。\n"
"システムディレクトリが書き込み可能かどうか確認してください。"

#: ../DistUpgrade/DistUpgradeController.py:497
msgid "Include latest updates from the Internet?"
msgstr "インターネットからの最新のアップデート情報を取得しますか？"

#: ../DistUpgrade/DistUpgradeController.py:498
msgid ""
"The upgrade system can use the internet to automatically download the latest "
"updates and install them during the upgrade.  If you have a network "
"connection this is highly recommended.\n"
"\n"
"The upgrade will take longer, but when it is complete, your system will be "
"fully up to date.  You can choose not to do this, but you should install the "
"latest updates soon after upgrading.\n"
"If you answer 'no' here, the network is not used at all."
msgstr ""
"アップグレードシステムは、ネットワークを利用したシステムのアップグレードに対応しています。最新のパッケージを自動的にダウンロードし、アップグレード時に併せ"
"てインストールできるため、ネットワークへの接続が可能なら、この方法を使うことを強く推奨します。\n"
"\n"
"アップグレードには時間がかかりますが、ネットワークを利用すれば、完了時に最新のアップデータが導入された状態になります。ネットワークを利用しないアップグレー"
"ドも可能ですが、この場合はアップグレードが完了した後で、さらにアップデータをインストールする必要があります。\n"
"ここで「いいえ」を選択すると、アップグレードにネットワークを利用しません。"

#: ../DistUpgrade/DistUpgradeController.py:729
#, python-format
msgid "disabled on upgrade to %s"
msgstr "%sへのアップグレード時に無効化されました"

#: ../DistUpgrade/DistUpgradeController.py:762
msgid "No valid mirror found"
msgstr "利用可能なミラーが見つかりません"

#: ../DistUpgrade/DistUpgradeController.py:753
#, python-format
msgid ""
"While scanning your repository information no mirror entry for the upgrade "
"was found. This can happen if you run a internal mirror or if the mirror "
"information is out of date.\n"
"\n"
"Do you want to rewrite your 'sources.list' file anyway? If you choose 'Yes' "
"here it will update all '%s' to '%s' entries.\n"
"If you select 'No' the upgrade will cancel."
msgstr ""
"システムに設定されたリポジトリ情報を確認しましたが、アップグレードに利用可能なミラーサーバーのエントリが見つかりませんでした。プライベートなミラーサーバー"
"を利用していたり、ミラー情報が古い可能性があります。\n"
"\n"
"ミラーサーバーの設定ファイル 'sources.list' をとにかく編集しますか？　「はい」を選択すると、'%s' エントリは '%s' "
"に置き換わります。\n"
"「いいえ」を選択すると、アップグレードをキャンセルします。"

#. hm, still nothing useful ...
#: ../DistUpgrade/DistUpgradeController.py:783
msgid "Generate default sources?"
msgstr "標準のリポジトリ設定ファイルを生成しますか？"

#: ../DistUpgrade/DistUpgradeController.py:784
#, python-format
msgid ""
"After scanning your 'sources.list' no valid entry for '%s' was found.\n"
"\n"
"Should default entries for '%s' be added? If you select 'No', the upgrade "
"will cancel."
msgstr ""
"システムの 'sources.list' を確認しましたが、有効な '%s' のためのエントリが見つかりません。\n"
"\n"
"'%s' のためのデフォルト設定エントリを追加しますか？　「いいえ」を選択すると、アップグレードはキャンセルされます。"

#: ../DistUpgrade/DistUpgradeController.py:819
msgid "Repository information invalid"
msgstr "リポジトリ情報が無効です"

#: ../DistUpgrade/DistUpgradeController.py:820
msgid ""
"Upgrading the repository information resulted in a invalid file so a bug "
"reporting process is being started."
msgstr "リポジトリの情報を更新した際にファイルが破損しました。それによりバグ報告のプロセスが開始されました。"

#: ../DistUpgrade/DistUpgradeController.py:827
msgid "Third party sources disabled"
msgstr "サードパーティが提供するリポジトリを使わない設定にしました"

#: ../DistUpgrade/DistUpgradeController.py:828
msgid ""
"Some third party entries in your sources.list were disabled. You can re-"
"enable them after the upgrade with the 'software-properties' tool or your "
"package manager."
msgstr ""
"sources.list にあるサードパーティが提供するリポジトリを使わない設定にしました。アップグレード完了後、'ソフトウェアソース' "
"ツールもしくはパッケージマネージャーを使って再び利用可能な設定にすることができます。"

#: ../DistUpgrade/DistUpgradeController.py:870
msgid "Package in inconsistent state"
msgid_plural "Packages in inconsistent state"
msgstr[0] "矛盾した状態のパッケージ"

#: ../DistUpgrade/DistUpgradeController.py:873
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Please reinstall the package manually or "
"remove it from the system."
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archive can be found for them. Please reinstall the packages manually "
"or remove them from the system."
msgstr[0] ""
"パッケージ '%s' は "
"矛盾した状態にあり再インストールが必要ですが、そのためのアーカイブを見つけることができません。パッケージを手動で再インストールするか、システムからパッケー"
"ジを削除してください。"

#: ../DistUpgrade/DistUpgradeController.py:921
msgid "Error during update"
msgstr "アップデート中にエラーが発生しました"

#: ../DistUpgrade/DistUpgradeController.py:922
msgid ""
"A problem occurred during the update. This is usually some sort of network "
"problem, please check your network connection and retry."
msgstr ""
"アップデート中に問題が発生しました。通常、これはネットワークにおける何らかの問題です。ネットワーク接続が可能であることをチェックし、あらためて試してくださ"
"い。"

#: ../DistUpgrade/DistUpgradeController.py:931
msgid "Not enough free disk space"
msgstr "ディスクの空き領域が足りません"

#: ../DistUpgrade/DistUpgradeController.py:932
#, python-format
msgid ""
"The upgrade has aborted. The upgrade needs a total of %s free space on disk "
"'%s'. Please free at least an additional %s of disk space on '%s'. Empty "
"your trash and remove temporary packages of former installations using 'sudo "
"apt-get clean'."
msgstr ""
"アップグレードを中断しました。アップグレードを行うには、 %s の空き容量がディスク %s に必要です。少なくともあと %s の空き容量をディスク %s "
"に作ってください。ゴミ箱を空にしたり、'sudo apt-get clean' を実行して今までにインストールした一時パッケージを削除してください。"

#. calc the dist-upgrade and see if the removals are ok/expected
#. do the dist-upgrade
#: ../DistUpgrade/DistUpgradeController.py:961
#: ../DistUpgrade/DistUpgradeController.py:1743
msgid "Calculating the changes"
msgstr "変更点を確認中"

#. ask the user
#: ../DistUpgrade/DistUpgradeController.py:993
msgid "Do you want to start the upgrade?"
msgstr "アップグレードを開始しますか？"

#: ../DistUpgrade/DistUpgradeController.py:1066
msgid "Upgrade canceled"
msgstr "アップグレードをキャンセルしました"

#: ../DistUpgrade/DistUpgradeController.py:1067
msgid ""
"The upgrade will cancel now and the original system state will be restored. "
"You can resume the upgrade at a later time."
msgstr "アップグレードはすぐにキャンセルされ、システムは元の状態に戻ります。後でアップグレードをやり直すことができます。"

#: ../DistUpgrade/DistUpgradeController.py:1073
#: ../DistUpgrade/DistUpgradeController.py:1197
msgid "Could not download the upgrades"
msgstr "アップグレードに必要なデータをダウンロードできません"

#: ../DistUpgrade/DistUpgradeController.py:1074
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. All files downloaded so far have been kept."
msgstr ""
"アップグレードを中断しました。インターネット接続またはインストールメディアを確認して再度試してください。これまでにダウンロードしたすべてのファイルは保存さ"
"れています。"

#. FIXME: strings are not good, but we are in string freeze
#. currently
#: ../DistUpgrade/DistUpgradeController.py:1148
#: ../DistUpgrade/DistUpgradeController.py:1185
#: ../DistUpgrade/DistUpgradeController.py:1290
msgid "Error during commit"
msgstr "反映中にエラーが発生しました"

#. generate a new cache
#: ../DistUpgrade/DistUpgradeController.py:1150
#: ../DistUpgrade/DistUpgradeController.py:1187
#: ../DistUpgrade/DistUpgradeController.py:1329
msgid "Restoring original system state"
msgstr "システムを元に戻しています"

#: ../DistUpgrade/DistUpgradeController.py:1151
#: ../DistUpgrade/DistUpgradeController.py:1166
#: ../DistUpgrade/DistUpgradeController.py:1188
msgid "Could not install the upgrades"
msgstr "アップグレードをインストールできません"

#. invoke the frontend now and show a error message
#: ../DistUpgrade/DistUpgradeController.py:1156
msgid ""
"The upgrade has aborted. Your system could be in an unusable state. A "
"recovery will run now (dpkg --configure -a)."
msgstr ""
"アップグレードを中断しました。システムが不安定な状態の可能性があります。今からリカバリーを実行します。(dpkg --configure -a)"

#: ../DistUpgrade/DistUpgradeController.py:1161
#, python-format
msgid ""
"\n"
"\n"
"Please report this bug in a browser at "
"http://bugs.launchpad.net/ubuntu/+source/ubuntu-release-upgrader/+filebug "
"and attach the files in /var/log/dist-upgrade/ to the bug report.\n"
"%s"
msgstr ""
"\n"
"\n"
"ブラウザから http://bugs.launchpad.net/ubuntu/+source/ubuntu-release-"
"upgrader/+filebug を開き /var/log/dist-upgrade/ にあるファイルを添付し、このバグを報告してください。\n"
"%s"

#: ../DistUpgrade/DistUpgradeController.py:1198
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. "
msgstr "アップグレードを中断しました。インターネット接続またはインストールメディアを確認して、もう一度実行してください。 "

#: ../DistUpgrade/DistUpgradeController.py:1278
msgid "Remove obsolete packages?"
msgstr "サポートが中止された（あるいはリポジトリに存在しない）パッケージを削除しますか？"

#: ../DistUpgrade/DistUpgradeController.py:1279
#: ../data/gtkbuilder/DistUpgrade.ui.h:8
msgid "_Keep"
msgstr "そのまま(_K)"

#: ../DistUpgrade/DistUpgradeController.py:1279
msgid "_Remove"
msgstr "削除(_R)"

#: ../DistUpgrade/DistUpgradeController.py:1291
msgid ""
"A problem occurred during the clean-up. Please see the below message for "
"more information. "
msgstr "クリーンアップ中に問題が発生しました。詳細情報は下記のメッセージを参照してください。 "

#. FIXME: instead of error out, fetch and install it
#. here
#: ../DistUpgrade/DistUpgradeController.py:1367
msgid "Required depends is not installed"
msgstr "依存するパッケージがインストールされていません"

#: ../DistUpgrade/DistUpgradeController.py:1368
#, python-format
msgid "The required dependency '%s' is not installed. "
msgstr "依存するパッケージ '%s' がインストールされていません。 "

#. sanity check (check for ubuntu-desktop, brokenCache etc)
#. then open the cache (again)
#: ../DistUpgrade/DistUpgradeController.py:1636
#: ../DistUpgrade/DistUpgradeController.py:1701
msgid "Checking package manager"
msgstr "パッケージマネージャーをチェック中です"

#: ../DistUpgrade/DistUpgradeController.py:1641
msgid "Preparing the upgrade failed"
msgstr "アップグレードの準備に失敗しました"

#: ../DistUpgrade/DistUpgradeController.py:1642
msgid ""
"Preparing the system for the upgrade failed so a bug reporting process is "
"being started."
msgstr "アップグレードのための準備に失敗しました。それによりバグ報告のプロセスが開始されました。"

#: ../DistUpgrade/DistUpgradeController.py:1656
msgid "Getting upgrade prerequisites failed"
msgstr "アップグレードの事前作業に失敗しました"

#: ../DistUpgrade/DistUpgradeController.py:1657
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"Additionally, a bug reporting process is being started."
msgstr ""
"アップグレードに必要なものを取得できませんでした。アップグレードはすぐに中止され、システムは以前の状態に戻されます。\n"
"\n"
"同時にバグ報告のプロセスが開始されました。"

#: ../DistUpgrade/DistUpgradeController.py:1685
msgid "Updating repository information"
msgstr "リポジトリ情報のアップデート"

#: ../DistUpgrade/DistUpgradeController.py:1692
msgid "Failed to add the cdrom"
msgstr "cdromの追加に失敗しました"

#: ../DistUpgrade/DistUpgradeController.py:1693
msgid "Sorry, adding the cdrom was not successful."
msgstr "cdrom の追加に失敗しました。"

#: ../DistUpgrade/DistUpgradeController.py:1724
msgid "Invalid package information"
msgstr "利用できないパッケージ情報です"

#: ../DistUpgrade/DistUpgradeController.py:1725
#, python-format
msgid ""
"After updating your package information, the essential package '%s' could "
"not be located. This may be because you have no official mirrors listed in "
"your software sources, or because of excessive load on the mirror you are "
"using. See /etc/apt/sources.list for the current list of configured software "
"sources.\n"
"In the case of an overloaded mirror, you may want to try the upgrade again "
"later."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1749
#: ../DistUpgrade/DistUpgradeController.py:1805
msgid "Fetching"
msgstr "取得中"

#: ../DistUpgrade/DistUpgradeController.py:1755
#: ../DistUpgrade/DistUpgradeController.py:1809
msgid "Upgrading"
msgstr "アップグレード中です"

#. don't abort here, because it would restore the sources.list
#: ../DistUpgrade/DistUpgradeController.py:1760
#: ../DistUpgrade/DistUpgradeController.py:1811
#: ../DistUpgrade/DistUpgradeController.py:1818
#: ../DistUpgrade/DistUpgradeController.py:1829
msgid "Upgrade complete"
msgstr "アップグレードが完了しました"

#: ../DistUpgrade/DistUpgradeController.py:1761
#: ../DistUpgrade/DistUpgradeController.py:1812
#: ../DistUpgrade/DistUpgradeController.py:1819
msgid ""
"The upgrade has completed but there were errors during the upgrade process."
msgstr "アップグレードは完了しましたが、アップグレード中にいくつかのエラーが発生しました。"

#: ../DistUpgrade/DistUpgradeController.py:1768
msgid "Searching for obsolete software"
msgstr "古いソフトウェアを検索しています"

#: ../DistUpgrade/DistUpgradeController.py:1781
msgid "System upgrade is complete."
msgstr "システムのアップグレードが完了しました。"

#: ../DistUpgrade/DistUpgradeController.py:1830
msgid "The partial upgrade was completed."
msgstr "部分的なアップグレードが完了しました。"

#: ../DistUpgrade/DistUpgradeFetcher.py:123
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:119
msgid "Could not find the release notes"
msgstr "リリースノートが見つかりません"

#: ../DistUpgrade/DistUpgradeFetcher.py:124
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:120
msgid "The server may be overloaded. "
msgstr "サーバーに大きな負荷がかかっています。 "

#: ../DistUpgrade/DistUpgradeFetcher.py:136
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:124
msgid "Could not download the release notes"
msgstr "リリースノートをダウンロードできません"

#: ../DistUpgrade/DistUpgradeFetcher.py:137
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:125
msgid "Please check your internet connection."
msgstr "インターネット接続を確認してください。"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:75
#, python-format
msgid "authenticate '%(file)s' against '%(signature)s' "
msgstr "「%(signature)s」を用いて「%(file)s」の認証を行ないます "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:136
#, python-format
msgid "extracting '%s'"
msgstr "'%s' の展開中"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:157
#: ../DistUpgrade/DistUpgradeFetcherCore.py:158
msgid "Could not run the upgrade tool"
msgstr "アップグレード・ツールを実行できません"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:159
msgid ""
"This is most likely a bug in the upgrade tool. Please report it as a bug "
"using the command 'ubuntu-bug ubuntu-release-upgrader-core'."
msgstr ""
"これはアップグレードツールのバグと思われます。これを 'ubuntu-bug ubuntu-release-upgrader-core' "
"というコマンドを実行してバグとして報告してください。"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:236
msgid "Upgrade tool signature"
msgstr "ツールの署名のアップグレード"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:243
msgid "Upgrade tool"
msgstr "ツールのアップグレード"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:277
msgid "Failed to fetch"
msgstr "取得に失敗しました"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:278
msgid "Fetching the upgrade failed. There may be a network problem. "
msgstr "アップグレードの取得に失敗しました。おそらくネットワークの問題です。 "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:282
msgid "Authentication failed"
msgstr "認証に失敗しました"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:283
msgid ""
"Authenticating the upgrade failed. There may be a problem with the network "
"or with the server. "
msgstr "アップグレードの認証に失敗しました。おそらくネットワークまたはサーバーの問題です。 "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:288
msgid "Failed to extract"
msgstr "抽出に失敗しました"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:289
msgid ""
"Extracting the upgrade failed. There may be a problem with the network or "
"with the server. "
msgstr "アップグレードの展開に失敗しました。おそらくネットワークまたはサーバーの問題です。 "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:294
msgid "Verification failed"
msgstr "認証に失敗しました"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:295
msgid ""
"Verifying the upgrade failed.  There may be a problem with the network or "
"with the server. "
msgstr "アップグレードの検証に失敗しました。ネットワーク接続もしくはサーバーに問題があるかもしれません。 "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:309
#: ../DistUpgrade/DistUpgradeFetcherCore.py:315
msgid "Can not run the upgrade"
msgstr "アップグレードを実行できません"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:310
msgid ""
"This usually is caused by a system where /tmp is mounted noexec. Please "
"remount without noexec and run the upgrade again."
msgstr ""
"この現象は、通常/tmpがnoexecでマウントされている場合にシステムで発生します。noexecを付けずに再マウントして、再度アップグレードを実行してく"
"ださい。"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:316
#, python-format
msgid "The error message is '%s'."
msgstr "エラーメッセージは'%s'です。"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:70
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:101
msgid "Upgrade"
msgstr "アップグレード"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:105
#: ../data/gtkbuilder/ReleaseNotes.ui.h:1
msgid "Release Notes"
msgstr "リリースノート"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:147
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:160
msgid "Downloading additional package files..."
msgstr "追加パッケージのダウンロード..."

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:162
#, python-format
msgid "File %s of %s at %sB/s"
msgstr "ファイル %s / %s (%sB/s)"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:166
#, python-format
msgid "File %s of %s"
msgstr "ファイル %s / %s"

#. print("mediaChange %s %s" % (medium, drive))
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:173
#: ../DistUpgrade/DistUpgradeViewGtk.py:114
#: ../DistUpgrade/DistUpgradeViewGtk3.py:115
#: ../DistUpgrade/DistUpgradeViewKDE.py:196
#, python-format
msgid "Please insert '%s' into the drive '%s'"
msgstr "メディア '%s' をドライブ '%s' に挿入してください"

#. change = QMessageBox.question(None, _("Media Change"), msg,
#. QMessageBox.Ok, QMessageBox.Cancel)
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:176
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:177
#: ../DistUpgrade/DistUpgradeViewKDE.py:197
msgid "Media Change"
msgstr "メディアの交換"

#: ../DistUpgrade/DistUpgradeQuirks.py:208
msgid "evms in use"
msgstr "evms は使用中です"

#: ../DistUpgrade/DistUpgradeQuirks.py:209
msgid ""
"Your system uses the 'evms' volume manager in /proc/mounts. The 'evms' "
"software is no longer supported, please switch it off and run the upgrade "
"again when this is done."
msgstr ""
"システムは/proc/mountsでボリュームマネジャとして 'evms' を使っています。'evms' "
"ソフトウェアはもうサポートされていません。オフにしてからアップグレードしてください。"

#: ../DistUpgrade/DistUpgradeQuirks.py:511
msgid "Your graphics hardware may not be fully supported in Ubuntu 13.04."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:248
msgid ""
"Running the 'unity' desktop environment is not fully supported by your "
"graphics hardware. You will maybe end up in a very slow environment after "
"the upgrade. Our advice is to keep the LTS version for now. For more "
"information see "
"https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForUnity3D Do you still "
"want to continue with the upgrade?"
msgstr ""
"'unity' "
"デスクトップ環境は、お使いのグラフィックハードウェアによるサポートが不完全です。アップグレード後にとても遅い環境になるかもしれません。現時点での私たちのア"
"ドバイスは、LTSバージョンのままにしておくことです。詳細は "
"https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForUnity3D "
"を確認してください。それでもアップグレードを続けますか？"

#: ../DistUpgrade/DistUpgradeQuirks.py:272
msgid ""
"Your graphics hardware may not be fully supported in Ubuntu 12.04 LTS."
msgstr "現在使用中のグラフィックハードウェアのサポートは Ubuntu 12.04 LTS では不完全な可能性があります。"

#: ../DistUpgrade/DistUpgradeQuirks.py:274
msgid ""
"The support in Ubuntu 12.04 LTS for your Intel graphics hardware is limited "
"and you may encounter problems after the upgrade. For more information see "
"https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForI8xx Do you want to "
"continue with the upgrade?"
msgstr ""
"現在使用中の Intel 製グラフィックハードウェアは Ubuntu 12.04 LTS "
"では制限付きのサポートとなっているため、アップグレード後に不具合が発生する可能性があります。詳しくは "
"https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForI8xx "
"をご覧ください。アップグレードを続行しますか?"

#: ../DistUpgrade/DistUpgradeQuirks.py:294
msgid ""
"Upgrading may reduce desktop effects, and performance in games and other "
"graphically intensive programs."
msgstr ""
"アップグレードによって、デスクトップ効果（3Dデスクトップ）やゲーム、グラフィックに強く依存するその他のプログラムなどのパフォーマンスが低下するかもしれま"
"せん。"

#: ../DistUpgrade/DistUpgradeQuirks.py:564
#: ../DistUpgrade/DistUpgradeQuirks.py:592
msgid ""
"This computer is currently using the NVIDIA 'nvidia' graphics driver. No "
"version of this driver is available that works with your video card in "
"Ubuntu 10.04 LTS.\n"
"\n"
"Do you want to continue?"
msgstr ""
"現在、このコンピューターはNVIDIA 'nvidia' グラフィックドライバーを利用しています。Ubuntu 10.04 LTS "
"では、このハードウェアで動作可能なドライバーのバージョンはありません。\n"
"\n"
"作業を続けますか？"

#: ../DistUpgrade/DistUpgradeQuirks.py:298
msgid ""
"This computer is currently using the AMD 'fglrx' graphics driver. No version "
"of this driver is available that works with your hardware in Ubuntu 10.04 "
"LTS.\n"
"\n"
"Do you want to continue?"
msgstr ""
"現在、このコンピューターはAMD 'fglrx' グラフィックドライバーを利用しています。Ubuntu 10.04 LTS "
"では、このハードウェアで動作可能なドライバーのバージョンはありません。\n"
"\n"
"作業を続けますか？"

#: ../DistUpgrade/DistUpgradeQuirks.py:333
msgid "No i686 CPU"
msgstr "i686 CPU ではありません"

#: ../DistUpgrade/DistUpgradeQuirks.py:334
msgid ""
"Your system uses an i586 CPU or a CPU that does not have the 'cmov' "
"extension. All packages were built with optimizations requiring i686 as the "
"minimal architecture. It is not possible to upgrade your system to a new "
"Ubuntu release with this hardware."
msgstr ""
"あなたのコンピューターは、i586 CPU または 'cmov' 拡張命令に対応していない CPU "
"を使用しています。すべてのパッケージは、最低限のアーキテクチャとして i686 "
"を必要とする最適化でビルドされています。このハードウェアでは、新しいバージョンの Ubuntu にアップグレードすることができません。"

#: ../DistUpgrade/DistUpgradeQuirks.py:370
msgid "No ARMv6 CPU"
msgstr "ARMv6 準拠ではない CPU です"

#: ../DistUpgrade/DistUpgradeQuirks.py:371
msgid ""
"Your system uses an ARM CPU that is older than the ARMv6 architecture. All "
"packages in karmic were built with optimizations requiring ARMv6 as the "
"minimal architecture. It is not possible to upgrade your system to a new "
"Ubuntu release with this hardware."
msgstr ""
"このシステムでは ARM CPU が使われていますが、ARMv6 アーキテクチャより古いもののようです。karmic の全てのパッケージは、ARMv6 "
"アーキテクチャへの対応が必須な最適化オプションを利用してビルドされています。このハードウェアでは新しい Ubuntu "
"のリリースにアップグレードできません。"

#: ../DistUpgrade/DistUpgradeQuirks.py:391
msgid "No init available"
msgstr "initデーモンが見つかりません"

#: ../DistUpgrade/DistUpgradeQuirks.py:392
msgid ""
"Your system appears to be a virtualised environment without an init daemon, "
"e.g. Linux-VServer. Ubuntu 10.04 LTS cannot function within this type of "
"environment, requiring an update to your virtual machine configuration "
"first.\n"
"\n"
"Are you sure you want to continue?"
msgstr ""
"このシステムは、initデーモンの関与なしで稼働している仮想環境のようです（例：Linux-VServer）。 Ubuntu 10.04 LTS "
"ではこのタイプの環境を稼働させることができません。アップグレードの前に、仮想マシン設定を設定しなおす必要があります。\n"
"\n"
"本当に作業を進めてよろしいですか？"

#: ../DistUpgrade/DistUpgradeMain.py:64
msgid "Sandbox upgrade using aufs"
msgstr "aufsを使用したサンドボックスアップグレード"

#: ../DistUpgrade/DistUpgradeMain.py:66
msgid "Use the given path to search for a cdrom with upgradable packages"
msgstr "アップグレードパッケージが含まれたCD-ROMへのパスを指定してください"

#: ../DistUpgrade/DistUpgradeMain.py:72
msgid ""
"Use frontend. Currently available: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"
msgstr ""
"フロントエンドを使用してください。現在利用可能なもの: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"

#: ../DistUpgrade/DistUpgradeMain.py:75
msgid "*DEPRECATED* this option will be ignored"
msgstr "*DEPRECATED* このオプションは無視されます"

#: ../DistUpgrade/DistUpgradeMain.py:78
msgid "Perform a partial upgrade only (no sources.list rewriting)"
msgstr "部分アップグレードだけを実行します（sources.listを書き換えません）"

#: ../DistUpgrade/DistUpgradeMain.py:81
msgid "Disable GNU screen support"
msgstr "GNU screen のサポートを無効にする"

#: ../DistUpgrade/DistUpgradeMain.py:83
msgid "Set datadir"
msgstr "datadirを設定"

#: ../DistUpgrade/DistUpgradeViewGtk.py:135
#: ../DistUpgrade/DistUpgradeViewGtk3.py:136
#: ../DistUpgrade/DistUpgradeViewKDE.py:210
msgid "Fetching is complete"
msgstr "取得が完了しました"

#: ../DistUpgrade/DistUpgradeViewGtk.py:149
#: ../DistUpgrade/DistUpgradeViewGtk3.py:151
#: ../DistUpgrade/DistUpgradeViewKDE.py:226
#, python-format
msgid "Fetching file %li of %li at %sB/s"
msgstr "%li / %li を取得中（%s B/s）"

#: ../DistUpgrade/DistUpgradeViewGtk.py:151
#: ../DistUpgrade/DistUpgradeViewGtk.py:298
#: ../DistUpgrade/DistUpgradeViewGtk3.py:153
#: ../DistUpgrade/DistUpgradeViewGtk3.py:310
#: ../DistUpgrade/DistUpgradeViewKDE.py:227
#: ../DistUpgrade/DistUpgradeViewKDE.py:375
#, python-format
msgid "About %s remaining"
msgstr "残り時間 約%s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:154
#: ../DistUpgrade/DistUpgradeViewGtk3.py:156
#: ../DistUpgrade/DistUpgradeViewKDE.py:229
#, python-format
msgid "Fetching file %li of %li"
msgstr "%li / %li を取得中です"

#. FIXME: add support for the timeout
#. of the terminal (to display something useful then)
#. -> longer term, move this code into python-apt
#: ../DistUpgrade/DistUpgradeViewGtk.py:185
#: ../DistUpgrade/DistUpgradeViewGtk3.py:187
#: ../DistUpgrade/DistUpgradeViewKDE.py:266
msgid "Applying changes"
msgstr "変更を適用しています"

#. we do not report followup errors from earlier failures
#: ../DistUpgrade/DistUpgradeViewGtk.py:210
#: ../DistUpgrade/DistUpgradeViewGtk3.py:213
#: ../DistUpgrade/DistUpgradeViewKDE.py:279
msgid "dependency problems - leaving unconfigured"
msgstr "依存関係の問題 - 設定を見送ります"

#: ../DistUpgrade/DistUpgradeViewGtk.py:215
#: ../DistUpgrade/DistUpgradeViewGtk3.py:218
#: ../DistUpgrade/DistUpgradeViewKDE.py:281
#, python-format
msgid "Could not install '%s'"
msgstr "'%s' がインストールできません"

#: ../DistUpgrade/DistUpgradeViewGtk.py:216
#: ../DistUpgrade/DistUpgradeViewGtk3.py:219
#: ../DistUpgrade/DistUpgradeViewKDE.py:282
#, python-format
msgid ""
"The upgrade will continue but the '%s' package may not be in a working "
"state. Please consider submitting a bug report about it."
msgstr ""
"アップグレードを続けますが、'%s' パッケージが動かない状態にある可能性があります。この件に関してバグレポートを送信することを検討してください。"

#. self.expander.set_expanded(True)
#: ../DistUpgrade/DistUpgradeViewGtk.py:233
#: ../DistUpgrade/DistUpgradeViewGtk3.py:236
#: ../DistUpgrade/DistUpgradeViewKDE.py:303
#, python-format
msgid ""
"Replace the customized configuration file\n"
"'%s'?"
msgstr ""
"以下のカスタマイズ済みの設定ファイルを置き換えますか？\n"
"'%s'"

#: ../DistUpgrade/DistUpgradeViewGtk.py:234
#: ../DistUpgrade/DistUpgradeViewGtk3.py:237
#: ../DistUpgrade/DistUpgradeViewKDE.py:304
msgid ""
"You will lose any changes you have made to this configuration file if you "
"choose to replace it with a newer version."
msgstr "より新しいバージョンと入れ換えた場合、この構成ファイルへの変更内容は失われます。"

#: ../DistUpgrade/DistUpgradeViewGtk.py:253
#: ../DistUpgrade/DistUpgradeViewGtk3.py:257
#: ../DistUpgrade/DistUpgradeViewKDE.py:327
msgid "The 'diff' command was not found"
msgstr "'diff' コマンドが見つかりません"

#: ../DistUpgrade/DistUpgradeViewGtk.py:466
#: ../DistUpgrade/DistUpgradeViewGtk3.py:478
#: ../DistUpgrade/DistUpgradeViewText.py:100
msgid "A fatal error occurred"
msgstr "致命的なエラーが起こりました"

#: ../DistUpgrade/DistUpgradeViewGtk.py:467
#: ../DistUpgrade/DistUpgradeViewGtk3.py:479
msgid ""
"Please report this as a bug (if you haven't already) and include the files "
"/var/log/dist-upgrade/main.log and /var/log/dist-upgrade/apt.log in your "
"report. The upgrade has aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"（まだ報告されていなければ）この現象をバグとして報告してください。報告には /var/log/dist-upgrade/main.log と "
"/var/log/dist-upgrade/apt.log を添付する必要があります。アップグレードは完了しませんでした。\n"
"変更前のsources.listは/etc/apt/sources.list.distUpgradeに保存されています。"

#: ../DistUpgrade/DistUpgradeViewGtk.py:484
#: ../DistUpgrade/DistUpgradeViewGtk3.py:496
msgid "Ctrl-c pressed"
msgstr "Ctrl-c が入力されました"

#: ../DistUpgrade/DistUpgradeViewGtk.py:485
#: ../DistUpgrade/DistUpgradeViewGtk3.py:497
msgid ""
"This will abort the operation and may leave the system in a broken state. "
"Are you sure you want to do that?"
msgstr "これは操作を中断することになり、システムを壊れた状態にしてしまうかもしれません。本当に実行しますか？"

#. append warning
#: ../DistUpgrade/DistUpgradeViewGtk.py:633
#: ../DistUpgrade/DistUpgradeViewGtk3.py:630
msgid "To prevent data loss close all open applications and documents."
msgstr "データが失われることを避けるため、利用中のアプリケーションとドキュメントを閉じてください。"

#: ../DistUpgrade/DistUpgradeViewGtk.py:647
#: ../DistUpgrade/DistUpgradeViewGtk3.py:644
#, python-format
msgid "No longer supported by Canonical (%s)"
msgstr "Canonical によってサポートされなくなりました (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:648
#: ../DistUpgrade/DistUpgradeViewGtk3.py:645
#, python-format
msgid "<b>Downgrade (%s)</b>"
msgstr "<b>ダウングレード (%s)</b>"

#: ../DistUpgrade/DistUpgradeViewGtk.py:649
#: ../DistUpgrade/DistUpgradeViewGtk3.py:646
#, python-format
msgid "Remove (%s)"
msgstr "削除 (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:650
#: ../DistUpgrade/DistUpgradeViewGtk3.py:647
#, python-format
msgid "No longer needed (%s)"
msgstr "もう不要なもの (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:651
#: ../DistUpgrade/DistUpgradeViewGtk3.py:648
#, python-format
msgid "Install (%s)"
msgstr "インストール (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:652
#: ../DistUpgrade/DistUpgradeViewGtk3.py:649
#, python-format
msgid "Upgrade (%s)"
msgstr "アップグレード (%s)"

#: ../DistUpgrade/DistUpgradeViewKDE.py:339
msgid "Show Difference >>>"
msgstr "差分を表示 >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:342
msgid "<<< Hide Difference"
msgstr "<<< 差分を隠す"

#: ../DistUpgrade/DistUpgradeViewKDE.py:558
msgid "Error"
msgstr "エラー"

#: ../DistUpgrade/DistUpgradeViewKDE.py:572
msgid "&Cancel"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:817
msgid "&Close"
msgstr "閉じる(&C)"

#: ../DistUpgrade/DistUpgradeViewKDE.py:622
msgid "Show Terminal >>>"
msgstr "端末を表示 >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:625
msgid "<<< Hide Terminal"
msgstr "<<< 端末を隠す"

#: ../DistUpgrade/DistUpgradeViewKDE.py:705
msgid "Information"
msgstr "情報"

#: ../DistUpgrade/DistUpgradeViewKDE.py:755
#: ../DistUpgrade/DistUpgradeViewKDE.py:800
#: ../DistUpgrade/DistUpgradeViewKDE.py:803
#: ../data/gtkbuilder/DistUpgrade.ui.h:7
msgid "Details"
msgstr "詳細"

#: ../DistUpgrade/DistUpgradeViewKDE.py:781
#, python-format
msgid "No longer supported %s"
msgstr "サポートされなくなりました %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:783
#, python-format
msgid "Remove %s"
msgstr "%s を削除"

#: ../DistUpgrade/DistUpgradeViewKDE.py:785
#: ../DistUpgrade/DistUpgradeViewText.py:194
#, python-format
msgid "Remove (was auto installed) %s"
msgstr "(自動インストールされた) %s を削除"

#: ../DistUpgrade/DistUpgradeViewKDE.py:787
#, python-format
msgid "Install %s"
msgstr "インストール %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:789
#, python-format
msgid "Upgrade %s"
msgstr "アップグレード %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:813
#: ../DistUpgrade/DistUpgradeViewText.py:242
msgid "Restart required"
msgstr "再起動が必要です"

#: ../DistUpgrade/DistUpgradeViewKDE.py:813
msgid "<b><big>Restart the system to complete the upgrade</big></b>"
msgstr "<b><big>アップグレードを完了するには、システムの再起動が必要です</big></b>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:816
#: ../data/gtkbuilder/DistUpgrade.ui.h:14
msgid "_Restart Now"
msgstr "すぐに再起動(_R)"

#. FIXME make this user friendly
#: ../DistUpgrade/DistUpgradeViewKDE.py:834
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly advised to resume the upgrade."
msgstr ""
"<b><big>実行中のアップグレードをキャンセルしますか？</big></b>\n"
"\n"
"アップグレードをキャンセルしてしまうと、システムが不安定な状態になる恐れがあります。アップグレードを再開することを強くお勧めします。"

#: ../DistUpgrade/DistUpgradeViewKDE.py:838
msgid "Cancel Upgrade?"
msgstr "アップグレードをキャンセルしますか?"

#: ../DistUpgrade/DistUpgradeView.py:73
#, python-format
msgid "%li day"
msgid_plural "%li days"
msgstr[0] "%li 日"

#: ../DistUpgrade/DistUpgradeView.py:75
#, python-format
msgid "%li hour"
msgid_plural "%li hours"
msgstr[0] "%li 時間"

#: ../DistUpgrade/DistUpgradeView.py:77
#, python-format
msgid "%li minute"
msgid_plural "%li minutes"
msgstr[0] "%li 分"

#: ../DistUpgrade/DistUpgradeView.py:78
#, python-format
msgid "%li second"
msgid_plural "%li seconds"
msgstr[0] "%li 秒"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_days)s %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#. 
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#. 
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:94
#, python-format
msgid "%(str_days)s %(str_hours)s"
msgstr "%(str_days)s %(str_hours)s"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#. 
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#. 
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:112
#, python-format
msgid "%(str_hours)s %(str_minutes)s"
msgstr "%(str_hours)s %(str_minutes)s"

#. 56 kbit
#. 1Mbit = 1024 kbit
#: ../DistUpgrade/DistUpgradeView.py:163
#, python-format
msgid ""
"This download will take about %s with a 1Mbit DSL connection and about %s "
"with a 56k modem."
msgstr "このダウンロードは 1Mbit DSL 接続で約 %s 、56k モデムで約 %s かかります。"

#. if we have a estimated speed, use it
#: ../DistUpgrade/DistUpgradeView.py:167
#, python-format
msgid "This download will take about %s with your connection. "
msgstr "このダウンロードは約 %s かかります。 "

#. Declare these translatable strings from the .ui files here so that
#. xgettext picks them up.
#: ../DistUpgrade/DistUpgradeView.py:271
#: ../data/gtkbuilder/DistUpgrade.ui.h:21
msgid "Preparing to upgrade"
msgstr "アップグレードの準備"

#: ../DistUpgrade/DistUpgradeView.py:272
msgid "Getting new software channels"
msgstr "新しいソフトウェア・チャンネルの取得"

#: ../DistUpgrade/DistUpgradeView.py:273
#: ../data/gtkbuilder/DistUpgrade.ui.h:23
msgid "Getting new packages"
msgstr "新しいパッケージの取得"

#: ../DistUpgrade/DistUpgradeView.py:274
#: ../data/gtkbuilder/DistUpgrade.ui.h:26
msgid "Installing the upgrades"
msgstr "アップグレードのインストール"

#: ../DistUpgrade/DistUpgradeView.py:275
#: ../data/gtkbuilder/DistUpgrade.ui.h:25
msgid "Cleaning up"
msgstr "クリーンアップ"

#: ../DistUpgrade/DistUpgradeView.py:360
#, python-format
msgid ""
"%(amount)d installed package is no longer supported by Canonical. You can "
"still get support from the community."
msgid_plural ""
"%(amount)d installed packages are no longer supported by Canonical. You can "
"still get support from the community."
msgstr[0] ""
"%(amount)d 個のインストール済みパッケージは Canonical "
"によってサポートされなくなりました。ただしコミュニティからのサポートは受けることができます。"

#. FIXME: make those two separate lines to make it clear
#. that the "%" applies to the result of ngettext
#: ../DistUpgrade/DistUpgradeView.py:369
#, python-format
msgid "%d package is going to be removed."
msgid_plural "%d packages are going to be removed."
msgstr[0] "%d 個のパッケージが削除されます。"

#: ../DistUpgrade/DistUpgradeView.py:374
#, python-format
msgid "%d new package is going to be installed."
msgid_plural "%d new packages are going to be installed."
msgstr[0] "%d 個の新規パッケージがインストールされます。"

#: ../DistUpgrade/DistUpgradeView.py:380
#, python-format
msgid "%d package is going to be upgraded."
msgid_plural "%d packages are going to be upgraded."
msgstr[0] "%d 個のパッケージがアップグレードされます。"

#: ../DistUpgrade/DistUpgradeView.py:388
#, python-format
msgid ""
"\n"
"\n"
"You have to download a total of %s. "
msgstr ""
"\n"
"\n"
"合計 %s をダウンロードする必要があります。 "

#: ../DistUpgrade/DistUpgradeView.py:393
msgid ""
"Installing the upgrade can take several hours. Once the download has "
"finished, the process cannot be canceled."
msgstr "アップグレードをインストールするのに数時間かかることがあります。ダウンロードが完了してしまうと、処理はキャンセルできません。"

#: ../DistUpgrade/DistUpgradeView.py:397
msgid ""
"Fetching and installing the upgrade can take several hours. Once the "
"download has finished, the process cannot be canceled."
msgstr "アップグレードの取得とインストールには数時間かかることがあります。ダウンロードが完了してしまうと、処理はキャンセルできません。"

#: ../DistUpgrade/DistUpgradeView.py:402
msgid "Removing the packages can take several hours. "
msgstr "パッケージの削除に数時間かかることがあります。 "

#. FIXME: this should go into DistUpgradeController
#: ../DistUpgrade/DistUpgradeView.py:407
msgid "The software on this computer is up to date."
msgstr "このコンピューターのソフトウェアは最新です。"

#: ../DistUpgrade/DistUpgradeView.py:408
msgid ""
"There are no upgrades available for your system. The upgrade will now be "
"canceled."
msgstr "システムに適用可能なアップグレードはありません。アップグレードは中止されます。"

#: ../DistUpgrade/DistUpgradeView.py:421
msgid "Reboot required"
msgstr "再起動が必要です"

#: ../DistUpgrade/DistUpgradeView.py:422
msgid ""
"The upgrade is finished and a reboot is required. Do you want to do this now?"
msgstr "アップグレードが終了しました。再起動が必要です。今すぐ自動で再起動しますか？"

#: ../DistUpgrade/DistUpgradeViewText.py:101
msgid ""
"Please report this as a bug and include the files /var/log/dist-"
"upgrade/main.log and /var/log/dist-upgrade/apt.log in your report. The "
"upgrade has aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"この現象をバグとして報告してください。報告には /var/log/dist-upgrade/main.log と /var/log/dist-"
"upgrade/apt.log を添付する必要があります。アップグレードは完了しませんでした。\n"
"変更前のsources.listは/etc/apt/sources.list.distUpgradeに保存されています。"

#: ../DistUpgrade/DistUpgradeViewText.py:125
msgid "Aborting"
msgstr "中断します"

#: ../DistUpgrade/DistUpgradeViewText.py:130
msgid "Demoted:\n"
msgstr "サポートレベルの格下げ:\n"

#: ../DistUpgrade/DistUpgradeViewText.py:137
msgid "To continue please press [ENTER]"
msgstr "続けるには [ENTER] キーを押してください"

#: ../DistUpgrade/DistUpgradeViewText.py:169
#: ../DistUpgrade/DistUpgradeViewText.py:208
#: ../DistUpgrade/DistUpgradeViewText.py:215
msgid "Continue [yN] "
msgstr "続行する[yN] "

#: ../DistUpgrade/DistUpgradeViewText.py:169
#: ../DistUpgrade/DistUpgradeViewText.py:208
msgid "Details [d]"
msgstr "詳細 [d]"

#. TRANSLATORS: the "y" is "yes"
#. TRANSLATORS: first letter of a positive (yes) answer
#: ../DistUpgrade/DistUpgradeViewText.py:174
#: ../DistUpgrade/DistUpgradeViewText.py:218
msgid "y"
msgstr "y"

#. TRANSLATORS: the "n" is "no"
#. TRANSLATORS: first letter of a negative (no) answer
#: ../DistUpgrade/DistUpgradeViewText.py:177
#: ../DistUpgrade/DistUpgradeViewText.py:225
msgid "n"
msgstr "n"

#. TRANSLATORS: the "d" is "details"
#: ../DistUpgrade/DistUpgradeViewText.py:180
msgid "d"
msgstr "d"

#: ../DistUpgrade/DistUpgradeViewText.py:185
#, python-format
msgid "No longer supported: %s\n"
msgstr "サポートされなくなりました: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:190
#, python-format
msgid "Remove: %s\n"
msgstr "削除: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:200
#, python-format
msgid "Install: %s\n"
msgstr "インストール: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:205
#, python-format
msgid "Upgrade: %s\n"
msgstr "アップグレード: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:222
msgid "Continue [Yn] "
msgstr "続ける [Yn] "

#: ../DistUpgrade/DistUpgradeViewText.py:243
msgid ""
"To finish the upgrade, a restart is required.\n"
"If you select 'y' the system will be restarted."
msgstr ""
"アップグレードを完了するには再起動が必要です。\n"
"'Y' を選択すると再起動します。"

#: ../DistUpgrade/GtkProgress.py:73
#, python-format
msgid "Downloading file %(current)li of %(total)li with %(speed)s/s"
msgstr "ファイル %(current)li / %(total)li をダウンロード中 (%(speed)s/秒)"

#: ../DistUpgrade/GtkProgress.py:79
#, python-format
msgid "Downloading file %(current)li of %(total)li"
msgstr "ファイル %(current)li / %(total)li をダウンロード中"

#: ../data/gtkbuilder/AcquireProgress.ui.h:1
#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:7
msgid "Show progress of individual files"
msgstr "個別のファイルの進捗を表示"

#: ../data/gtkbuilder/DistUpgrade.ui.h:1
msgid "_Cancel Upgrade"
msgstr "アップグレードをキャンセル(_C)"

#: ../data/gtkbuilder/DistUpgrade.ui.h:2
msgid "_Resume Upgrade"
msgstr "アップグレードを再開(_R)"

#: ../data/gtkbuilder/DistUpgrade.ui.h:3
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly adviced to resume the upgrade."
msgstr ""
"<b><big>アップグレードをキャンセルしますか？</big></b>\n"
"\n"
"アップグレードをキャンセルすると、おそらくシステムは不安定な状態になります。アップグレードを再開することを強くおすすめします。"

#: ../data/gtkbuilder/DistUpgrade.ui.h:6
msgid "_Start Upgrade"
msgstr "アップグレードを開始(_S)"

#: ../data/gtkbuilder/DistUpgrade.ui.h:9
msgid "_Replace"
msgstr "置き換える(_R)"

#: ../data/gtkbuilder/DistUpgrade.ui.h:10
msgid "Difference between the files"
msgstr "ファイル同士の差異"

#: ../data/gtkbuilder/DistUpgrade.ui.h:11
msgid "_Report Bug"
msgstr "バグを報告する(_R)"

#: ../data/gtkbuilder/DistUpgrade.ui.h:12
msgid "_Continue"
msgstr "続行する(_C)"

#: ../data/gtkbuilder/DistUpgrade.ui.h:13
msgid "<b><big>Start the upgrade?</big></b>"
msgstr "<b><big>アップグレードを開始しますか？</big></b>"

#: ../data/gtkbuilder/DistUpgrade.ui.h:15
msgid ""
"<b><big>Restart the system to complete the upgrade</big></b>\n"
"\n"
"Please save your work before continuing."
msgstr ""
"<b><big>アップグレードを完了するには再起動してください</big></b>\n"
"\n"
"先へ進む前に、他のアプリケーションで行っているすべての作業を保存してください。"

#: ../data/gtkbuilder/DistUpgrade.ui.h:18
msgid "Distribution Upgrade"
msgstr "ディストリビューションのアップグレード"

#: ../data/gtkbuilder/DistUpgrade.ui.h:19
msgid "<b><big>Upgrading Ubuntu to version 13.04</big></b>"
msgstr ""

#: ../data/gtkbuilder/DistUpgrade.ui.h:20
msgid "    "
msgstr "    "

#: ../data/gtkbuilder/DistUpgrade.ui.h:22
msgid "Setting new software channels"
msgstr "新しいソフトウェア・チャンネルを設定しています"

#: ../data/gtkbuilder/DistUpgrade.ui.h:24
msgid "Restarting the computer"
msgstr "コンピューターの再起動"

#: ../data/gtkbuilder/DistUpgrade.ui.h:27
msgid "Terminal"
msgstr "端末"

#: ../data/gtkbuilder/ReleaseNotes.ui.h:2
msgid "_Upgrade"
msgstr "アップグレード(_U)"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:1
msgid ""
"<b>A new version of Ubuntu is available. Would you like to upgrade?</b>"
msgstr "<b>新しいバージョンの Ubuntu が利用可能です。アップグレードしますか?</b>"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:2
msgid "Don't Upgrade"
msgstr "アップグレードしない"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:3
msgid "Ask Me Later"
msgstr "次回にたずねる"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:4
msgid "Yes, Upgrade Now"
msgstr "今すぐアップグレードする"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:5
msgid "You have declined to upgrade to the new Ubuntu"
msgstr "新しいUbuntuへのアップグレードを拒絶"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:6
msgid ""
"You can upgrade at a later time by opening Software Updater and click on "
"\"Upgrade\"."
msgstr "後でアップグレードするには、ソフトウェアアップデーターを開き \"アップグレード\" をクリックします。"

#: ../data/com.ubuntu.release-upgrader.policy.in.h:1
msgid "Perform a release upgrade"
msgstr "リリースアップグレードを実行する"

#: ../data/com.ubuntu.release-upgrader.policy.in.h:2
msgid "To upgrade Ubuntu, you need to authenticate."
msgstr "Ubuntuをアップグレードするには、認証が必要です。"

#: ../data/com.ubuntu.release-upgrader.policy.in.h:3
msgid "Perform a partial upgrade"
msgstr "部分アップグレードを行う"

#: ../data/com.ubuntu.release-upgrader.policy.in.h:4
msgid "To perform a partial upgrade, you need to authenticate."
msgstr "部分的なアップグレードを実行するには、認証が必要です。"

#: ../do-partial-upgrade:67 ../do-release-upgrade:69
msgid "Show version and exit"
msgstr "バージョンを表示して終了"

#: ../do-partial-upgrade:70 ../do-release-upgrade:76
msgid "Directory that contains the data files"
msgstr "データファイルの含まれるディレクトリ"

#: ../do-partial-upgrade:73 ../do-release-upgrade:89
msgid "Run the specified frontend"
msgstr "特定のフロントエンドで実行"

#: ../do-partial-upgrade:90
msgid "Running partial upgrade"
msgstr "部分的なアップグレードを実行"

#: ../do-release-upgrade:31
msgid "Downloading the release upgrade tool"
msgstr "リリースアップグレードツールのダウンロード"

#: ../do-release-upgrade:72 ../check-new-release-gtk:177
msgid "Check if upgrading to the latest devel release is possible"
msgstr "最新の開発リリースへのアップデートが利用可能かどうかチェックする"

#: ../do-release-upgrade:79 ../check-new-release-gtk:181
msgid ""
"Try upgrading to the latest release using the upgrader from $distro-proposed"
msgstr "アップグレードソフトウェアを使って $distro-proposed から最新のリリースへのアップグレードを試す"

#: ../do-release-upgrade:83
msgid ""
"Run in a special upgrade mode.\n"
"Currently 'desktop' for regular upgrades of a desktop system and 'server' "
"for server systems are supported."
msgstr ""
"特別なアップグレードモードで実行する。\n"
"現在、デスクトップシステムの標準的なアップグレードを行う 'desktop' オプションと、サーバーシステム向けの 'server' "
"オプションがサポートされています。"

#: ../do-release-upgrade:91
msgid "Test upgrade with a sandbox aufs overlay"
msgstr "aufsオーバレイを実験環境に用いてのテストアップグレード"

#: ../do-release-upgrade:94
msgid ""
"Check only if a new distribution release is available and report the result "
"via the exit code"
msgstr "新しいディストリビューション・リリースが利用可能かどうかチェックし、終了コードで結果を通知する"

#: ../do-release-upgrade:108
msgid "Checking for a new Ubuntu release"
msgstr "新しい Ubuntu のリリースをチェックしています"

#: ../do-release-upgrade:121
msgid "Your Ubuntu release is not supported anymore."
msgstr "このバージョンのUbuntuは既にサポートが打ち切られています。"

#: ../do-release-upgrade:122
msgid ""
"For upgrade information, please visit:\n"
"%(url)s\n"
msgstr ""
"アップグレード情報は以下を参照:\n"
"%(url)s\n"

#: ../do-release-upgrade:128
msgid "No new release found"
msgstr "新しくリリースされたものはありません"

#: ../do-release-upgrade:133
msgid "Release upgrade not possible right now"
msgstr "今はリリースアップグレードができません。"

#: ../do-release-upgrade:134
#, c-format
msgid ""
"The release upgrade can not be performed currently, please try again later. "
"The server reported: '%s'"
msgstr "リリースアップグレードが現在実行できないので後でもう一度試してください。サーバーの報告は以下のとおりです: '%s'"

#: ../do-release-upgrade:140
#, c-format
msgid "New release '%s' available."
msgstr "新しいリリース '%s' が利用可能になっています。"

#: ../do-release-upgrade:141
msgid "Run 'do-release-upgrade' to upgrade to it."
msgstr "'do-release-upgrade' を実行してアップグレードしてください"

#: ../check-new-release-gtk:113
msgid "Ubuntu %(version)s Upgrade Available"
msgstr "Ubuntu %(version)s のアップグレードが利用可能です"

#: ../check-new-release-gtk:144
#, c-format
msgid "You have declined the upgrade to Ubuntu %s"
msgstr "Ubuntu %s へのアップグレードを拒絶"

#: ../check-new-release-gtk:186
msgid "Add debug output"
msgstr "デバッグ出力を追加"

#~ msgid "Authentication is required to perform a partial upgrade"
#~ msgstr "部分アップグレードを行うのに認証が必要です"

#~ msgid "Authentication is required to perform a release upgrade"
#~ msgstr "リリースアップグレードを行うのに認証が必要です"
