# translation of pa.po to Punjabi
# This file is distributed under the same license as the PACKAGE package.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER.
# Amanpreet Singh Alam <amanpreetalam@yahoo.com>, 2005.
#
msgid ""
msgstr ""
"Project-Id-Version: pa\n"
"Report-Msgid-Bugs-To: sebastian.heinlein@web.de\n"
"POT-Creation-Date: 2009-10-23 19:49+0000\n"
"PO-Revision-Date: 2009-10-06 01:19+0000\n"
"Last-Translator: Launchpad Translations Administrators "
"<rosetta@launchpad.net>\n"
"Language-Team: Punjabi <fedora-transa-pa@redhat.com>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Launchpad-Export-Date: 2009-10-26 14:52+0000\n"
"X-Generator: Launchpad (build Unknown)\n"

#. TRANSLATORS: download size is 0
#: ../DistUpgrade/utils.py:278 ../UpdateManager/Core/utils.py:278
msgid "0 KB"
msgstr ""

#. TRANSLATORS: download size of very small updates
#: ../DistUpgrade/utils.py:281 ../UpdateManager/Core/utils.py:281
msgid "1 KB"
msgstr ""

#. TRANSLATORS: download size of small updates, e.g. "250 KB"
#: ../DistUpgrade/utils.py:284 ../UpdateManager/Core/utils.py:284
#, python-format
msgid "%.0f KB"
msgstr ""

#. TRANSLATORS: download size of updates, e.g. "2.3 MB"
#: ../DistUpgrade/utils.py:287 ../UpdateManager/Core/utils.py:287
#, python-format
msgid "%.1f MB"
msgstr ""

#. TRANSLATORS: %s is a country
#: ../DistUpgrade/distro.py:208 ../DistUpgrade/distro.py:423
#, python-format
msgid "Server for %s"
msgstr ""

#. More than one server is used. Since we don't handle this case
#. in the user interface we set "custom servers" to true and
#. append a list of all used servers
#: ../DistUpgrade/distro.py:226 ../DistUpgrade/distro.py:232
#: ../DistUpgrade/distro.py:248
msgid "Main server"
msgstr ""

#: ../DistUpgrade/distro.py:252
msgid "Custom servers"
msgstr ""

#: ../DistUpgrade/DistUpgradeAptCdrom.py:131
msgid "Could not calculate sources.list entry"
msgstr ""

#: ../DistUpgrade/DistUpgradeAptCdrom.py:234
msgid ""
"Unable to locate any package files, perhaps this is not a Ubuntu Disc or the "
"wrong architecture?"
msgstr ""

#: ../DistUpgrade/DistUpgradeAptCdrom.py:277
msgid "Failed to add the CD"
msgstr ""

#: ../DistUpgrade/DistUpgradeAptCdrom.py:278
#, python-format
msgid ""
"There was a error adding the CD, the upgrade will abort. Please report this "
"as a bug if this is a valid Ubuntu CD.\n"
"\n"
"The error message was:\n"
"'%s'"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:130
msgid "Remove package in bad state"
msgid_plural "Remove packages in bad state"
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeCache.py:133
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Do you want to remove this package now "
"to continue?"
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archives can be found for them. Do you want to remove these packages "
"now to continue?"
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeCache.py:332
msgid "Broken packages"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:333
msgid ""
"Your system contains broken packages that couldn't be fixed with this "
"software. Please fix them first using synaptic or apt-get before proceeding."
msgstr ""

#. FIXME: change the text to something more useful
#: ../DistUpgrade/DistUpgradeCache.py:609
#, python-format
msgid ""
"An unresolvable problem occurred while calculating the upgrade:\n"
"%s\n"
"\n"
" This can be caused by:\n"
" * Upgrading to a pre-release version of Ubuntu\n"
" * Running the current pre-release version of Ubuntu\n"
" * Unofficial software packages not provided by Ubuntu\n"
"\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:619
msgid "This is most likely a transient problem, please try again later."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:622
msgid ""
"If none of this applies, then please report this bug against the 'update-"
"manager' package and include the files in /var/log/dist-upgrade/ in the bug "
"report."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:628
#: ../UpdateManager/UpdateManager.py:749
msgid "Could not calculate the upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:678
msgid "Error authenticating some packages"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:679
msgid ""
"It was not possible to authenticate some packages. This may be a transient "
"network problem. You may want to try again later. See below for a list of "
"unauthenticated packages."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:699
#, python-format
msgid ""
"The package '%s' is marked for removal but it is in the removal blacklist."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:703
#, python-format
msgid "The essential package '%s' is marked for removal."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:712
#, python-format
msgid "Trying to install blacklisted version '%s'"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:812
#, python-format
msgid "Can not mark '%s' for upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:826
#, python-format
msgid "Can't install '%s'"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:827
msgid ""
"It was impossible to install a required package. Please report this as a "
"bug. "
msgstr ""

#. FIXME: provide a list
#: ../DistUpgrade/DistUpgradeCache.py:836
msgid "Can't guess meta-package"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:837
msgid ""
"Your system does not contain a ubuntu-desktop, kubuntu-desktop, xubuntu-"
"desktop or edubuntu-desktop package and it was not possible to detect which "
"version of Ubuntu you are running.\n"
" Please install one of the packages above first using synaptic or apt-get "
"before proceeding."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:85
msgid "Reading cache"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:185
msgid "Unable to get exclusive lock"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:186
msgid ""
"This usually means that another package management application (like apt-get "
"or aptitude) already running. Please close that application first."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:232
msgid "Upgrading over remote connection not supported"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:233
msgid ""
"You are running the upgrade over a remote ssh connection with a frontend "
"that does not support this. The upgrade will abort now. Please try without "
"ssh."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:244
msgid "Continue running under SSH?"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:245
#, python-format
msgid ""
"This session appears to be running under ssh. It is not recommended to "
"perform a upgrade over ssh currently because in case of failure it is harder "
"to recover.\n"
"\n"
"If you continue, a additional ssh daemon will be started at port '%s'.\n"
"Do you want to continue?"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:260
msgid "Starting additional sshd"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:261
#, python-format
msgid ""
"To make recovery in case of failure easier, an additional sshd will be "
"started on port '%s'. If anything goes wrong with the running ssh you can "
"still connect to the additional one.\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:331
#: ../DistUpgrade/DistUpgradeController.py:376
msgid "Can not upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:332
#, python-format
msgid "An upgrade from '%s' to '%s' is not supported with this tool."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:341
msgid "Sandbox setup failed"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:342
msgid "It was not possible to create the sandbox environment."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:348
msgid "Sandbox mode"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:349
#, python-format
msgid ""
"This upgrade is running in sandbox (test) mode. All changes are written to "
"'%s' and will be lost on the next reboot.\n"
"\n"
"*No* changes written to a systemdir from now until the next reboot are "
"permanent."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:377
msgid ""
"Your python install is corrupted. Please fix the '/usr/bin/python' symlink."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:403
msgid "Package 'debsig-verify' is installed"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:404
msgid ""
"The upgrade can not continue with that package installed.\n"
"Please remove it with synaptic or 'apt-get remove debsig-verify' first and "
"run the upgrade again."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:414
msgid "Include latest updates from the Internet?"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:415
msgid ""
"The upgrade system can use the internet to automatically download the latest "
"updates and install them during the upgrade.  If you have a network "
"connection this is highly recommended.\n"
"\n"
"The upgrade will take longer, but when it is complete, your system will be "
"fully up to date.  You can choose not to do this, but you should install the "
"latest updates soon after upgrading.\n"
"If you answer 'no' here, the network is not used at all."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:638
#, python-format
msgid "disabled on upgrade to %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:664
msgid "No valid mirror found"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:665
#, python-format
msgid ""
"While scanning your repository information no mirror entry for the upgrade "
"was found. This can happen if you run a internal mirror or if the mirror "
"information is out of date.\n"
"\n"
"Do you want to rewrite your 'sources.list' file anyway? If you choose 'Yes' "
"here it will update all '%s' to '%s' entries.\n"
"If you select 'No' the upgrade will cancel."
msgstr ""

#. hm, still nothing useful ...
#: ../DistUpgrade/DistUpgradeController.py:685
msgid "Generate default sources?"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:686
#, python-format
msgid ""
"After scanning your 'sources.list' no valid entry for '%s' was found.\n"
"\n"
"Should default entries for '%s' be added? If you select 'No', the upgrade "
"will cancel."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:721
msgid "Repository information invalid"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:722
msgid ""
"Upgrading the repository information resulted in a invalid file. Please "
"report this as a bug."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:728
msgid "Third party sources disabled"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:729
msgid ""
"Some third party entries in your sources.list were disabled. You can re-"
"enable them after the upgrade with the 'software-properties' tool or your "
"package manager."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:769
msgid "Package in inconsistent state"
msgid_plural "Packages in inconsistent state"
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeController.py:772
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Please reinstall the package manually or "
"remove it from the system."
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archive can be found for them. Please reinstall the packages manually "
"or remove them from the system."
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeController.py:820
msgid "Error during update"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:821
msgid ""
"A problem occurred during the update. This is usually some sort of network "
"problem, please check your network connection and retry."
msgstr ""

#. print "on_button_install_clicked"
#: ../DistUpgrade/DistUpgradeController.py:830
#: ../UpdateManager/UpdateManager.py:572
msgid "Not enough free disk space"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:831
#, python-format
msgid ""
"The upgrade is now aborted. The upgrade needs a total of %s free space on "
"disk '%s'. Please free at least an additional %s of disk space on '%s'. "
"Empty your trash and remove temporary packages of former installations using "
"'sudo apt-get clean'."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:871
msgid "Support for some applications ended"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:872
msgid ""
"Canonical Ltd. no longer provides support for the following software "
"packages. You can still get support from the community.\n"
"\n"
"If you have not enabled community maintained software (universe), these "
"packages will be suggested for removal at the end of the upgrade."
msgstr ""

#. calc the dist-upgrade and see if the removals are ok/expected
#. do the dist-upgrade
#: ../DistUpgrade/DistUpgradeController.py:881
#: ../DistUpgrade/DistUpgradeController.py:1551
msgid "Calculating the changes"
msgstr ""

#. ask the user if he wants to do the changes
#: ../DistUpgrade/DistUpgradeController.py:896
msgid "Do you want to start the upgrade?"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:952
msgid "Upgrade canceled"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:953
msgid ""
"The upgrade cancels now and the original system state is restored. You can "
"resume the upgrade at a later time."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:958
#: ../DistUpgrade/DistUpgradeController.py:1045
msgid "Could not download the upgrades"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:959
msgid ""
"The upgrade is now aborted. Please check your Internet connection or "
"installation media and try again. All files downloaded so far are kept."
msgstr ""

#. FIXME: strings are not good, but we are in string freeze
#. currently
#: ../DistUpgrade/DistUpgradeController.py:1012
#: ../DistUpgrade/DistUpgradeController.py:1135
msgid "Error during commit"
msgstr ""

#. generate a new cache
#: ../DistUpgrade/DistUpgradeController.py:1014
#: ../DistUpgrade/DistUpgradeController.py:1174
msgid "Restoring original system state"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1015
#: ../DistUpgrade/DistUpgradeController.py:1029
msgid "Could not install the upgrades"
msgstr ""

#. invoke the frontend now and show a error message
#: ../DistUpgrade/DistUpgradeController.py:1020
msgid ""
"The upgrade is now aborted. Your system could be in an unusable state. A "
"recovery will run now (dpkg --configure -a)."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1025
#, python-format
msgid ""
"\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"files in /var/log/dist-upgrade/ in the bug report.\n"
"%s"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1046
msgid ""
"The upgrade is now aborted. Please check your Internet connection or "
"installation media and try again. "
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1123
msgid "Remove obsolete packages?"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1124
#: ../DistUpgrade/DistUpgrade.ui.h:20
msgid "_Keep"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1124
msgid "_Remove"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1136
msgid ""
"A problem occurred during the clean-up. Please see the below message for "
"more information. "
msgstr ""

#. FIXME: instead of error out, fetch and install it
#. here
#: ../DistUpgrade/DistUpgradeController.py:1212
msgid "Required depends is not installed"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1213
#, python-format
msgid "The required dependency '%s' is not installed. "
msgstr ""

#. sanity check (check for ubuntu-desktop, brokenCache etc)
#. then open the cache (again)
#: ../DistUpgrade/DistUpgradeController.py:1458
#: ../DistUpgrade/DistUpgradeController.py:1525
msgid "Checking package manager"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1463
msgid "Preparing the upgrade failed"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1464
msgid ""
"Preparing the system for the upgrade failed. Please report this as a bug "
"against the 'update-manager' package and include the files in /var/log/dist-"
"upgrade/ in the bug report."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1480
msgid "Getting upgrade prerequisites failed"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1481
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"Please report this as a bug against the 'update-manager' package and include "
"the files in /var/log/dist-upgrade/ in the bug report."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1511
msgid "Updating repository information"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1539
msgid "Invalid package information"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1540
#, python-format
msgid ""
"After your package information was updated the essential package '%s' can "
"not be found anymore.\n"
"This indicates a serious error, please report this bug against the 'update-"
"manager' package and include the files in /var/log/dist-upgrade/ in the bug "
"report."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1557
#: ../DistUpgrade/DistUpgradeController.py:1605
msgid "Fetching"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1563
#: ../DistUpgrade/DistUpgradeController.py:1609
msgid "Upgrading"
msgstr ""

#. don't abort here, because it would restore the sources.list
#: ../DistUpgrade/DistUpgradeController.py:1568
#: ../DistUpgrade/DistUpgradeController.py:1611
#: ../DistUpgrade/DistUpgradeController.py:1618
#: ../DistUpgrade/DistUpgradeController.py:1623
msgid "Upgrade complete"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1569
#: ../DistUpgrade/DistUpgradeController.py:1612
#: ../DistUpgrade/DistUpgradeController.py:1619
msgid ""
"The upgrade is completed but there were errors during the upgrade process."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1576
msgid "Searching for obsolete software"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1581
msgid "System upgrade is complete."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1624
msgid "The partial upgrade was completed."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:149
msgid "No ARMv6 CPU"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:150
msgid ""
"Your system uses an ARM CPU that is older than the ARMv6 architecture. All "
"packages in karmic were built with optimizations requiring ARMv6 as the "
"minimal architecture. It is not possible to upgrade your system to a new "
"Ubuntu release with this hardware."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:164
msgid "No init available"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:165
msgid ""
"Your system appears to be a virtualised environment without an init daemon, "
"e.g. Linux-VServer. Ubuntu 9.10 cannot function within this type of "
"environment, requiring an update to your virtual machine configuration "
"first.\n"
"\n"
"Are you sure you want to continue?"
msgstr ""

#. TRANSLATORS: this string is not displayed in the 9.10 upgrade
#. (but it will be used for 8.04 -> 10.04 LTS upgrades)
#: ../DistUpgrade/DistUpgradeQuirks.py:186
#: ../DistUpgrade/DistUpgradeQuirks.py:271
#: ../DistUpgrade/DistUpgradeQuirks.py:298
msgid ""
"Upgrading may reduce desktop effects, and performance in games and other "
"graphically intensive programs."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:190
msgid ""
"This computer is currently using the AMD 'fglrx' graphics driver. No version "
"of this driver is available that works with your hardware in Ubuntu 10.04.\n"
"\n"
"Do you want to continue?"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:275
#: ../DistUpgrade/DistUpgradeQuirks.py:302
msgid ""
"This computer is currently using the NVIDIA 'nvidia' graphics driver. No "
"version of this driver is available that works with your video card in "
"Ubuntu 10.04.\n"
"\n"
"Do you want to continue?"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:472
msgid "evms in use"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:473
msgid ""
"Your system uses the 'evms' volume manager in /proc/mounts. The 'evms' "
"software is no longer supported, please switch it off and run the upgrade "
"again when this is done."
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:43
msgid "Sandbox upgrade using aufs"
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:45
msgid "Use the given path to search for a cdrom with upgradable packages"
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:51
msgid ""
"Use frontend. Currently available: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:54
msgid "*DEPRECATED* this option will be ignore"
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:57
msgid "Perform a partial upgrade only (no sources.list rewriting)"
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:59
msgid "Set datadir"
msgstr ""

#. print "mediaChange %s %s" % (medium, drive)
#: ../DistUpgrade/DistUpgradeViewGtk.py:106
#: ../DistUpgrade/DistUpgradeViewKDE.py:190
#: ../UpdateManager/DistUpgradeFetcherKDE.py:148
#, python-format
msgid "Please insert '%s' into the drive '%s'"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:125
#: ../DistUpgrade/DistUpgradeViewKDE.py:203
msgid "Fetching is complete"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:137
#: ../DistUpgrade/DistUpgradeViewKDE.py:216
#, python-format
msgid "Fetching file %li of %li at %sB/s"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:138
#: ../DistUpgrade/DistUpgradeViewGtk.py:273
#: ../DistUpgrade/DistUpgradeViewKDE.py:217
#: ../DistUpgrade/DistUpgradeViewKDE.py:357
#, python-format
msgid "About %s remaining"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:140
#: ../DistUpgrade/DistUpgradeViewKDE.py:219
#, python-format
msgid "Fetching file %li of %li"
msgstr ""

#. FIXME: add support for the timeout
#. of the terminal (to display something useful then)
#. -> longer term, move this code into python-apt
#: ../DistUpgrade/DistUpgradeViewGtk.py:172
#: ../DistUpgrade/DistUpgradeViewKDE.py:253
msgid "Applying changes"
msgstr ""

#. we do not report followup errors from earlier failures
#: ../DistUpgrade/DistUpgradeViewGtk.py:197
#: ../DistUpgrade/DistUpgradeViewKDE.py:266
msgid "dependency problems - leaving unconfigured"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:202
#: ../DistUpgrade/DistUpgradeViewKDE.py:268
#, python-format
msgid "Could not install '%s'"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:203
#: ../DistUpgrade/DistUpgradeViewKDE.py:269
#, python-format
msgid ""
"The upgrade will continue but the '%s' package may not be in a working "
"state. Please consider submitting a bug report about it."
msgstr ""

#. self.expander.set_expanded(True)
#: ../DistUpgrade/DistUpgradeViewGtk.py:219
#: ../DistUpgrade/DistUpgradeViewKDE.py:290
#, python-format
msgid ""
"Replace the customized configuration file\n"
"'%s'?"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:220
#: ../DistUpgrade/DistUpgradeViewKDE.py:291
msgid ""
"You will lose any changes you have made to this configuration file if you "
"choose to replace it with a newer version."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:233
#: ../DistUpgrade/DistUpgradeViewKDE.py:309
msgid "The 'diff' command was not found"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:419
#: ../DistUpgrade/DistUpgradeViewText.py:107
msgid "A fatal error occurred"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:420
msgid ""
"Please report this as a bug (if you haven't already) and include the files "
"/var/log/dist-upgrade/main.log and /var/log/dist-upgrade/apt.log in your "
"report. The upgrade is now aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:435
msgid "Ctrl-c pressed"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:436
msgid ""
"This will abort the operation and may leave the system in a broken state. "
"Are you sure you want to do that?"
msgstr ""

#. append warning
#: ../DistUpgrade/DistUpgradeViewGtk.py:581
msgid "To prevent data loss close all open applications and documents."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:595
#, python-format
msgid "<b>Downgrade %s</b>"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:597
#: ../DistUpgrade/DistUpgradeViewKDE.py:757
#, python-format
msgid "Remove %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:602
#: ../DistUpgrade/DistUpgradeViewKDE.py:759
#, python-format
msgid "Install %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk.py:604
#: ../DistUpgrade/DistUpgradeViewKDE.py:761
#, python-format
msgid "Upgrade %s"
msgstr ""

#. change = QMessageBox.question(None, _("Media Change"), msg, QMessageBox.Ok, QMessageBox.Cancel)
#: ../DistUpgrade/DistUpgradeViewKDE.py:191
#: ../UpdateManager/DistUpgradeFetcherKDE.py:150
msgid "Media Change"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:321
msgid "Show Difference >>>"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:324
msgid "<<< Hide Difference"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:538
msgid "Error"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:550
msgid "&Cancel"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:552
#: ../DistUpgrade/DistUpgradeViewKDE.py:789
msgid "&Close"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:598
msgid "Show Terminal >>>"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:601
msgid "<<< Hide Terminal"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:681
msgid "Information"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:731
#: ../DistUpgrade/DistUpgradeViewKDE.py:772
#: ../DistUpgrade/DistUpgradeViewKDE.py:775 ../DistUpgrade/DistUpgrade.ui.h:9
msgid "Details"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:785
#: ../DistUpgrade/DistUpgradeViewText.py:225
msgid "Restart required"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:785 ../DistUpgrade/DistUpgrade.ui.h:5
msgid "<b><big>Restart the system to complete the upgrade</big></b>"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:788 ../DistUpgrade/DistUpgrade.ui.h:23
msgid "_Restart Now"
msgstr ""

#. FIXME make this user friendly
#: ../DistUpgrade/DistUpgradeViewKDE.py:800
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly advised to resume the upgrade."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:804
msgid "Cancel Upgrade?"
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:60
#, python-format
msgid "%li day"
msgid_plural "%li days"
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeView.py:62
#, python-format
msgid "%li hour"
msgid_plural "%li hours"
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeView.py:64
#, python-format
msgid "%li minute"
msgid_plural "%li minutes"
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeView.py:65
#, python-format
msgid "%li second"
msgid_plural "%li seconds"
msgstr[0] ""
msgstr[1] ""

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_days)s %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#. 
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#. 
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:78
#, python-format
msgid "%(str_days)s %(str_hours)s"
msgstr ""

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#. 
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#. 
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:93
#, python-format
msgid "%(str_hours)s %(str_minutes)s"
msgstr ""

#. 56 kbit
#. 1Mbit = 1024 kbit
#: ../DistUpgrade/DistUpgradeView.py:114
#, python-format
msgid ""
"This download will take about %s with a 1Mbit DSL connection and about %s "
"with a 56k modem."
msgstr ""

#. if we have a estimated speed, use it
#: ../DistUpgrade/DistUpgradeView.py:118
#, python-format
msgid "This download will take about %s with your connection. "
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:212 ../DistUpgrade/DistUpgrade.ui.h:14
msgid "Preparing to upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:213
msgid "Getting new software channels"
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:214 ../DistUpgrade/DistUpgrade.ui.h:12
msgid "Getting new packages"
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:215 ../DistUpgrade/DistUpgrade.ui.h:13
msgid "Installing the upgrades"
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:216 ../DistUpgrade/DistUpgrade.ui.h:8
msgid "Cleaning up"
msgstr ""

#. FIXME: make those two separate lines to make it clear
#. that the "%" applies to the result of ngettext
#: ../DistUpgrade/DistUpgradeView.py:289
#, python-format
msgid "%d package is going to be removed."
msgid_plural "%d packages are going to be removed."
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeView.py:294
#, python-format
msgid "%d new package is going to be installed."
msgid_plural "%d new packages are going to be installed."
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeView.py:300
#, python-format
msgid "%d package is going to be upgraded."
msgid_plural "%d packages are going to be upgraded."
msgstr[0] ""
msgstr[1] ""

#: ../DistUpgrade/DistUpgradeView.py:305
#, python-format
msgid ""
"\n"
"\n"
"You have to download a total of %s. "
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:309
msgid ""
"Fetching and installing the upgrade can take several hours. Once the "
"download has finished, the process cannot be cancelled."
msgstr ""

#. FIXME: this should go into DistUpgradeController
#: ../DistUpgrade/DistUpgradeView.py:315 ../UpdateManager/UpdateManager.py:502
msgid "Your system is up-to-date"
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:316
msgid ""
"There are no upgrades available for your system. The upgrade will now be "
"canceled."
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:329
msgid "Reboot required"
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:330
msgid ""
"The upgrade is finished and a reboot is required. Do you want to do this now?"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:134
#: ../DistUpgrade/DistUpgradeFetcherCore.py:135
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:134
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:135
msgid "Could not run the upgrade tool"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:135
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:135
msgid ""
"This is most likely a bug in the upgrade tool. Please report it as a bug"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:204
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:204
msgid "Upgrade tool signature"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:207
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:207
msgid "Upgrade tool"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:237
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:237
msgid "Failed to fetch"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:238
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:238
msgid "Fetching the upgrade failed. There may be a network problem. "
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:242
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:242
msgid "Failed to extract"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:243
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:243
msgid ""
"Extracting the upgrade failed. There may be a problem with the network or "
"with the server. "
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:248
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:248
msgid "Verification failed"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:249
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:249
msgid ""
"Verifying the upgrade failed.  There may be a problem with the network or "
"with the server. "
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:254
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:254
msgid "Authentication failed"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:255
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:255
msgid ""
"Authenticating the upgrade failed. There may be a problem with the network "
"or with the server. "
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:263
#: ../DistUpgrade/DistUpgradeFetcherCore.py:269
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:263
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:269
msgid "Can not run the upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:264
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:264
msgid ""
"This usually is caused by a system were /tmp is mounted noexec. Please "
"remount without noexec and run the upgrade again."
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:270
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:270
#, python-format
msgid "The error message is '%s'."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:108
msgid ""
"Please report this as a bug and include the files /var/log/dist-"
"upgrade/main.log and /var/log/dist-upgrade/apt.log in your report. The "
"upgrade is now aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:132
msgid "Aborting"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:137
msgid "Demoted:\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:169
#: ../DistUpgrade/DistUpgradeViewText.py:191
#: ../DistUpgrade/DistUpgradeViewText.py:198
msgid "Continue [yN] "
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:169
#: ../DistUpgrade/DistUpgradeViewText.py:191
msgid "Details [d]"
msgstr ""

#. TRANSLATORS: the "y" is "yes"
#. TRANSLATORS: first letter of a positive (yes) answer
#: ../DistUpgrade/DistUpgradeViewText.py:173
#: ../DistUpgrade/DistUpgradeViewText.py:201
msgid "y"
msgstr ""

#. TRANSLATORS: the "n" is "no"
#. TRANSLATORS: first letter of a negative (no) answer
#: ../DistUpgrade/DistUpgradeViewText.py:176
#: ../DistUpgrade/DistUpgradeViewText.py:208
msgid "n"
msgstr ""

#. TRANSLATORS: the "d" is "details"
#: ../DistUpgrade/DistUpgradeViewText.py:179
msgid "d"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:183
#, python-format
msgid "Remove: %s\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:186
#, python-format
msgid "Install: %s\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:189
#, python-format
msgid "Upgrade: %s\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:205
msgid "Continue [Yn] "
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:226
msgid ""
"To finish the upgrade, a restart is required.\n"
"If you select 'y' the system will be restarted."
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:1
msgid "    "
msgstr "    "

#: ../DistUpgrade/DistUpgrade.ui.h:2
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly adviced to resume the upgrade."
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:6
msgid "<b><big>Start the upgrade?</big></b>"
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:7
msgid "<b><big>Upgrading Ubuntu to version 9.10</big></b>"
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:10
msgid "Difference between the files"
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:11
msgid "Distribution Upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:15
msgid "Restarting the computer"
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:16
msgid "Setting new software channels"
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:17
msgid "Terminal"
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:18
msgid "_Cancel Upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:19
msgid "_Continue"
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:21
msgid "_Replace"
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:22
msgid "_Report Bug"
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:24
msgid "_Resume Upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgrade.ui.h:25
msgid "_Start Upgrade"
msgstr ""

#: ../UpdateManager/backend/InstallBackendSynaptic.py:42
msgid "Please wait, this can take some time."
msgstr ""

#: ../UpdateManager/backend/InstallBackendSynaptic.py:44
msgid "Update is complete"
msgstr ""

#: ../UpdateManager/DistUpgradeFetcher.py:85
#: ../UpdateManager/DistUpgradeFetcherKDE.py:103
msgid "Could not find the release notes"
msgstr ""

#: ../UpdateManager/DistUpgradeFetcher.py:86
#: ../UpdateManager/DistUpgradeFetcherKDE.py:104
msgid "The server may be overloaded. "
msgstr ""

#: ../UpdateManager/DistUpgradeFetcher.py:96
#: ../UpdateManager/DistUpgradeFetcherKDE.py:108
msgid "Could not download the release notes"
msgstr ""

#: ../UpdateManager/DistUpgradeFetcher.py:97
#: ../UpdateManager/DistUpgradeFetcherKDE.py:109
msgid "Please check your internet connection."
msgstr ""

#: ../UpdateManager/DistUpgradeFetcherKDE.py:62
#: ../UpdateManager/DistUpgradeFetcherKDE.py:85
msgid "Upgrade"
msgstr ""

#: ../UpdateManager/DistUpgradeFetcherKDE.py:89
#: ../data/glade/UpdateManager.ui.h:12
msgid "Release Notes"
msgstr ""

#: ../UpdateManager/DistUpgradeFetcherKDE.py:128
#: ../UpdateManager/DistUpgradeFetcherKDE.py:141
#: ../UpdateManager/DistUpgradeFetcherKDE.py:143
msgid "Downloading additional package files..."
msgstr ""

#: ../UpdateManager/DistUpgradeFetcherKDE.py:141
#, python-format
msgid "File %s of %s at %sB/s"
msgstr ""

#: ../UpdateManager/DistUpgradeFetcherKDE.py:143
#, python-format
msgid "File %s of %s"
msgstr ""

#: ../UpdateManager/ChangelogViewer.py:70
msgid "Open Link in Browser"
msgstr ""

#: ../UpdateManager/ChangelogViewer.py:72
msgid "Copy Link to Clipboard"
msgstr ""

#: ../UpdateManager/GtkProgress.py:115
#, python-format
msgid "Downloading file %(current)li of %(total)li with %(speed)s/s"
msgstr ""

#: ../UpdateManager/GtkProgress.py:120
#, python-format
msgid "Downloading file %(current)li of %(total)li"
msgstr ""

#: ../UpdateManager/UpdateManager.py:303
#, python-format
msgid "Version %s: \n"
msgstr ""

#: ../UpdateManager/UpdateManager.py:360
msgid "Downloading list of changes..."
msgstr ""

#: ../UpdateManager/UpdateManager.py:400
msgid "_Uncheck All"
msgstr ""

#: ../UpdateManager/UpdateManager.py:406
msgid "_Check All"
msgstr ""

#: ../UpdateManager/UpdateManager.py:450
#, python-format
msgid "%s selected. Download size: %s"
msgstr ""

#: ../UpdateManager/UpdateManager.py:455
msgid "Unknown download size"
msgstr ""

#: ../UpdateManager/UpdateManager.py:463
msgid ""
"It is unknown when the package information was updated last. Please try "
"clicking on the 'Check' button to update the information."
msgstr ""

#: ../UpdateManager/UpdateManager.py:472
#, python-format
msgid "The package information was last updated %s day ago."
msgid_plural "The package information was last updated %s days ago."
msgstr[0] ""
msgstr[1] ""

#: ../UpdateManager/UpdateManager.py:476
#, python-format
msgid "The package information was last updated %s hour ago."
msgid_plural "The package information was last updated %s hours ago."
msgstr[0] ""
msgstr[1] ""

#: ../UpdateManager/UpdateManager.py:480
msgid "The package information was last updated less than one hour ago."
msgstr ""

#: ../UpdateManager/UpdateManager.py:500 ../data/glade/UpdateManager.ui.h:22
msgid ""
"Software updates correct errors, eliminate security vulnerabilities and "
"provide new features."
msgstr ""

#: ../UpdateManager/UpdateManager.py:519
msgid "Welcome to Ubuntu"
msgstr ""

#: ../UpdateManager/UpdateManager.py:520
msgid ""
"These software updates have been issued since Ubuntu was released. If you "
"don't want to install them now, choose \"Update Manager\" from the "
"Administration Menu later."
msgstr ""

#: ../UpdateManager/UpdateManager.py:523
msgid "Software updates are available for this computer"
msgstr ""

#: ../UpdateManager/UpdateManager.py:524
msgid ""
"If you don't want to install them now, choose \"Update Manager\" from the "
"Administration menu later."
msgstr ""

#: ../UpdateManager/UpdateManager.py:573
#, python-format
msgid ""
"The upgrade needs a total of %s free space on disk '%s'. Please free at "
"least an additional %s of disk space on '%s'. Empty your trash and remove "
"temporary packages of former installations using 'sudo apt-get clean'."
msgstr ""

#: ../UpdateManager/UpdateManager.py:610
#: ../UpdateManagerHildon/UpdateManagerHildon.py:114
msgid "Reading package information"
msgstr ""

#: ../UpdateManager/UpdateManager.py:727
msgid "Could not initialize the package information"
msgstr ""

#: ../UpdateManager/UpdateManager.py:728
msgid ""
"An unresolvable problem occurred while initializing the package "
"information.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:\n"
msgstr ""

#: ../UpdateManager/UpdateManager.py:750
msgid ""
"An unresolvable problem occurred while calculating the upgrade.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:"
msgstr ""

#: ../UpdateManager/UpdateManager.py:773
msgid " (New install)"
msgstr ""

#. TRANSLATORS: the b stands for Bytes
#: ../UpdateManager/UpdateManager.py:777
#, python-format
msgid "(Size: %s)"
msgstr ""

#: ../UpdateManager/UpdateManager.py:779
#, python-format
msgid "From version %(old_version)s to %(new_version)s"
msgstr ""

#: ../UpdateManager/UpdateManager.py:783
#, python-format
msgid "Version %s"
msgstr ""

#: ../UpdateManager/UpdateManager.py:796
msgid "Your Ubuntu release is not supported anymore"
msgstr ""

#: ../UpdateManager/UpdateManager.py:797
msgid ""
"You will not get any further security fixes or critical updates. Please "
"Upgrade to a later version of Ubuntu Linux."
msgstr ""

#: ../UpdateManager/UpdateManager.py:804
msgid "Upgrade information"
msgstr ""

#: ../UpdateManager/UpdateManager.py:831
#, python-format
msgid "<b>New Ubuntu release '%s' is available</b>"
msgstr ""

#. we assert a clean cache
#: ../UpdateManager/UpdateManager.py:870
msgid "Software index is broken"
msgstr ""

#: ../UpdateManager/UpdateManager.py:871
msgid ""
"It is impossible to install or remove any software. Please use the package "
"manager \"Synaptic\" or run \"sudo apt-get install -f\" in a terminal to fix "
"this issue at first."
msgstr ""

#: ../UpdateManagerHildon/UpdateManagerHildon.py:136
msgid "Downloading Package Information"
msgstr ""

#: ../UpdateManagerHildon/UpdateManagerHildon.py:137
msgid ""
"The repositories are being checked for new, removed, or updated software "
"packages"
msgstr ""

#: ../UpdateManagerHildon/UpdateManagerHildon.py:145
msgid "Downloading Package Updates"
msgstr ""

#: ../UpdateManagerHildon/UpdateManagerHildon.py:146
msgid ""
"The selected package updates are being downloaded and installed on the system"
msgstr ""

#: ../UpdateManagerHildon/UpdateManagerHildon.py:152
msgid "run_synaptic called with unknown action"
msgstr ""

#: ../UpdateManagerText/UpdateManagerText.py:26
msgid "Cancel"
msgstr ""

#: ../UpdateManagerText/UpdateManagerText.py:27
msgid "Install"
msgstr ""

#: ../UpdateManagerText/UpdateManagerText.py:45
msgid "Building Updates List"
msgstr ""

#: ../UpdateManagerText/UpdateManagerText.py:48
msgid ""
"\n"
"A normal upgrade can not be calculated, please run: \n"
"  sudo apt-get dist-upgrade\n"
"\n"
"\n"
"This can be caused by:\n"
" * A previous upgrade which didn't complete\n"
" * Problems with some of the installed software\n"
" * Unofficial software packages not provided by Ubuntu\n"
" * Normal changes of a pre-release version of Ubuntu"
msgstr ""

#: ../UpdateManagerText/UpdateManagerText.py:117
msgid "Downloading changelog"
msgstr ""

#: ../UpdateManager/Core/MyCache.py:108
#, python-format
msgid "Other updates (%s)"
msgstr ""

#: ../UpdateManager/Core/MyCache.py:227
#, python-format
msgid ""
"Changes for the versions:\n"
"%s\n"
"%s\n"
"\n"
msgstr ""

#: ../UpdateManager/Core/MyCache.py:229
msgid "This change is not coming from a source that supports changelogs."
msgstr ""

#: ../UpdateManager/Core/MyCache.py:237
#, python-format
msgid ""
"The changelog does not contain any relevant changes.\n"
"\n"
"Please use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"until the changes become available or try again later."
msgstr ""

#: ../UpdateManager/Core/MyCache.py:242
#, python-format
msgid ""
"The list of changes is not available yet.\n"
"\n"
"Please use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"until the changes become available or try again later."
msgstr ""

#: ../UpdateManager/Core/MyCache.py:248
msgid ""
"Failed to download the list of changes. \n"
"Please check your Internet connection."
msgstr ""

#: ../UpdateManager/Core/UpdateList.py:50
msgid "Failed to detect distribution"
msgstr ""

#: ../UpdateManager/Core/UpdateList.py:51
#, python-format
msgid "A error '%s' occurred while checking what system you are using."
msgstr ""

#: ../UpdateManager/Core/UpdateList.py:62
msgid "Important security updates"
msgstr ""

#: ../UpdateManager/Core/UpdateList.py:63
msgid "Recommended updates"
msgstr ""

#: ../UpdateManager/Core/UpdateList.py:64
msgid "Proposed updates"
msgstr ""

#: ../UpdateManager/Core/UpdateList.py:65
msgid "Backports"
msgstr ""

#: ../UpdateManager/Core/UpdateList.py:66
msgid "Distribution updates"
msgstr ""

#: ../UpdateManager/Core/UpdateList.py:71
msgid "Other updates"
msgstr ""

#: ../UpdateManager/Core/UpdateList.py:80
msgid "Previous selected"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:1
msgid ""
"<b><big>You must check for updates manually</big></b>\n"
"\n"
"Your system does not check for updates automatically. You can configure this "
"behavior in <i>Software Sources</i> on the <i>Updates</i> tab."
msgstr ""

#: ../data/glade/UpdateManager.ui.h:4
msgid "<big><b>Not all updates can be installed</b></big>"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:5
msgid "<big><b>Running on battery</b></big>"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:6
msgid "<big><b>Starting Update Manager</b></big>"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:7
msgid "Changes"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:8
msgid "Chec_k"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:9
msgid "Co_ntinue"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:10
msgid "Description"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:11
msgid "Description of update"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:13
msgid ""
"Run a partial upgrade, to install as many updates as possible. \n"
"\n"
"This can be caused by:\n"
" * A previous upgrade which didn't complete\n"
" * Problems with some of the installed software\n"
" * Unofficial software packages not provided by Ubuntu\n"
" * Normal changes of a pre-release version of Ubuntu"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:20
msgid "Settings..."
msgstr ""

#: ../data/glade/UpdateManager.ui.h:21
msgid "Show progress of individual files"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:23
msgid "U_pgrade"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:24 ../data/update-manager.desktop.in.h:3
#: ../data/update-manager-hildon.desktop.in.h:3
msgid "Update Manager"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:25
msgid "Your system is running on battery. Are you sure you want to continue?"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:26
msgid "_Hide this information in the future"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:27
msgid "_Install Updates"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:28
msgid "_Partial Upgrade"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:29
msgid "_Upgrade"
msgstr ""

#: ../data/glade/UpdateManager.ui.h:30
msgid "updates"
msgstr ""

#: ../data/update-manager.desktop.in.h:1
#: ../data/update-manager-hildon.desktop.in.h:1
msgid "Show and install available updates"
msgstr ""

#: ../data/update-manager.desktop.in.h:2
#: ../data/update-manager-hildon.desktop.in.h:2
msgid "Software Updates"
msgstr ""

#: ../data/update-manager.schemas.in.h:1
msgid "*deprecated* Check for new distribution releases"
msgstr ""

#: ../data/update-manager.schemas.in.h:2
msgid "Auto close the install window after successful install"
msgstr ""

#: ../data/update-manager.schemas.in.h:3
msgid "First run welcome message"
msgstr ""

#: ../data/update-manager.schemas.in.h:4
msgid ""
"If automatic checking for updates is disabled, you have to reload the "
"channel list manually. This option allows to hide the reminder shown in this "
"case."
msgstr ""

#: ../data/update-manager.schemas.in.h:5
msgid "If this key is set a first run welcome message will be presented."
msgstr ""

#: ../data/update-manager.schemas.in.h:6
msgid ""
"If this key is set the install window will be automatically closed on "
"successful installation."
msgstr ""

#: ../data/update-manager.schemas.in.h:7
msgid ""
"If this key is set the main update list window will show version information "
"(from version to version)."
msgstr ""

#: ../data/update-manager.schemas.in.h:8
msgid "Remind to reload the channel list"
msgstr ""

#: ../data/update-manager.schemas.in.h:9
msgid "Show details of an update"
msgstr ""

#: ../data/update-manager.schemas.in.h:10
msgid "Show version in update list"
msgstr ""

#: ../data/update-manager.schemas.in.h:11
msgid "Stores the size of the update-manager dialog"
msgstr ""

#: ../data/update-manager.schemas.in.h:12
msgid ""
"Stores the state of the expander that contains the list of changes and the "
"description"
msgstr ""

#: ../data/update-manager.schemas.in.h:13
msgid "The window size"
msgstr ""

#: ../data/update-manager.schemas.in.h:14
msgid ""
"This key is deprecated in favor of the file /etc/update-manager/release-"
"upgrades Check automatically if a new version of the current distribution is "
"available and offer to upgrade (if possible)."
msgstr ""

#: ../update-manager:56
msgid "Show version and exit"
msgstr ""

#: ../update-manager:59
msgid "Directory that contains the data files"
msgstr ""

#: ../update-manager:62
msgid "Check if a new Ubuntu release is available"
msgstr ""

#: ../update-manager:65 ../do-release-upgrade:23 ../check-new-release:24
msgid "Check if upgrading to the latest devel release is possible"
msgstr ""

#: ../update-manager:69
msgid "Upgrade using the latest proposed version of the release upgrader"
msgstr ""

#: ../update-manager:76
msgid "Do not focus on map when starting"
msgstr ""

#: ../update-manager:79
msgid "Try to run a dist-upgrade"
msgstr ""

#: ../update-manager:83 ../do-release-upgrade:39
msgid "Test upgrade with a sandbox aufs overlay"
msgstr ""

#: ../update-manager:103
msgid "Running partial upgrade"
msgstr ""

#: ../do-release-upgrade:27 ../check-new-release:28
msgid ""
"Try upgrading to the latest release using the upgrader from $distro-proposed"
msgstr ""

#: ../do-release-upgrade:31
msgid ""
"Run in a special upgrade mode.\n"
"Currently 'desktop' for regular upgrades of a desktop system and 'server' "
"for server systems are supported."
msgstr ""

#: ../do-release-upgrade:37
msgid "Run the specified frontend"
msgstr ""

#: ../do-release-upgrade:43
msgid "Checking for a new ubuntu release"
msgstr ""

#: ../do-release-upgrade:50
msgid "No new release found"
msgstr ""

#: ../check-new-release:32
#, c-format
msgid ""
"Do not output anything, just return %s if there is a new release and %s if "
"there is none."
msgstr ""

#: ../check-new-release:46
#, c-format
msgid "New release '%s' available."
msgstr ""

#: ../check-new-release:47
msgid "Run 'do-release-upgrade' to upgrade to it."
msgstr ""

#: ../Janitor/computerjanitor/exc.py:30
#, python-format
msgid "Unimplemented method: %s"
msgstr ""

#: ../Janitor/computerjanitor/file_cruft.py:46
msgid "A file on disk"
msgstr ""

#: ../Janitor/computerjanitor/package_cruft.py:45
msgid ".deb package"
msgstr ""

#: ../Janitor/computerjanitor/missing_package_cruft.py:33
msgid "Install missing package."
msgstr ""

#: ../Janitor/computerjanitor/missing_package_cruft.py:42
#, python-format
msgid "Package %s should be installed."
msgstr ""

#. pragma: no cover
#: ../Janitor/plugins/dpkg_status_plugin.py:36
#, python-format
msgid "%i obsolete entries in the status file"
msgstr ""

#: ../Janitor/plugins/dpkg_status_plugin.py:39
msgid "Obsolete entries in dpkg status"
msgstr ""

#. pragma: no cover
#: ../Janitor/plugins/dpkg_status_plugin.py:42
msgid "Obsolete dpkg status entries"
msgstr ""

#: ../Janitor/plugins/kdelibs4to5_plugin.py:39
msgid ""
"When upgrading, if kdelibs4-dev is installed, kdelibs5-dev needs to be "
"installed. See bugs.launchpad.net, bug #279621 for details."
msgstr ""

#: ../Janitor/plugins/langpack_manual_plugin.py:34
#, python-format
msgid "%s needs to be marked as manually installed."
msgstr ""

#: ../Janitor/plugins/remove_lilo_plugin.py:28
msgid ""
"Remove lilo since grub is also installed.(See bug #314004 for details.)"
msgstr ""
